SUBROUTINE ATUALIZA
!Esta sub-rotina é utilizada pela sub-rotina previsão para fazer a atualização
!de algumas variáveis no instante T0, em que inicia o ciclo de previsão. 
!A base para a atualização é a comparação com algum dado observado de vazão.
!nao serve para atualizar dados de planicie
USE VARS_MAIN
IMPLICIT NONE
REAL,ALLOCATABLE:: QCELAT(:),QMAT(:),PMSUPAT(:),PMSSUAT(:),PMSUBAT(:),QJAT(:),QRIOINIAT(:,:) ! VAZOES NA REDE INICIAL 
REAL,ALLOCATABLE:: VRSUPAT(:), VRSSUAT(:), VRSUBAT(:) ! VOLUMES ARMAZENADOS NO RIO NO INCIO DO INTERVALO DE TEMPO
REAL,ALLOCATABLE:: SSSUAT(:,:),SRADAT(:,:),SSUBAT(:,:) ! ARMAZENAMENTOS ATUALIZADOS
REAL,ALLOCATABLE:: QSUPAT(:),QSSUAT(:),QSUBAT(:) ! FLUXOS ATUALIZADOS
REAL EPS(NOBS),F1(NOBS),F2(NOBS),F3(NOBS),DIF1(NOBS),DIF2(NOBS) ! TOLERANCIA DO ERRO NA VAZAO, FATOR DE CORRECAO E ERROS NO INICIO E FINAL DA ITERACAO
REAL VT,VAUX
INTEGER POSTORIO(NOBS),NDIAS(NOBS) !INDICA O NUMERO DE POSTO QUE SERÁ USADO PARA CORRIGIR A VAZÃO NO RIO E QUANTAS OBSERVACOES SERAO USADAS
INTEGER ITR,IC,IB,IU,ITER,NBAC ! CONTADORES

! LE INFORMACOES BASICAS DO ARQUIVO PARPREV.HIG
OPEN(FILPREV,FILE=DIR_DADOS//'PARPREV.HIG',STATUS='OLD') !ARQUIVO COM dados DA PREVISAO
READ(FILPREV,76) TITULO ! LE TITULO
READ(FILPREV,76) TITULO ! LE TITULO
READ(FILPREV,*) (POSTORIO(IB),IB=1,NOBS) ! INDICA O NUMERO DO POSTO COM VAZAO OBSERVADA QUE SERA USADOS PARA CORRIGIR VAZAO EM CADA SUB-BACIA (0 NAO CORRIGE)

!INDICA POSTO QUE SERÁ USADO PARA CORRIGIR A VAZÃO NO RIO PARA CADA SUB-BACIA, POR EXEMPLO

!NÚMERO DE INTERVALOS DE TEMPO PARA CALCULAR A MEDIA E CALCULAR O ERRO E O FATOR DE CORRECAO
READ(FILPREV,*) ! LINHA EM BRANCO
READ(FILPREV,76) TITULO ! LE TITULO
READ(FILPREV,*) (NDIAS(IB),IB=1,NOBS) ! NUMERO DE INTERVALOS DE TEMPO PARA CALCULO DE VAZOES 

!TOLERANCIA ADMITIDA NO ERRO DA ESTIMATIVA DA VAZAO
READ(FILPREV,*) ! LINHA EM BRANCO
READ(FILPREV,76) TITULO ! LE TITULO
READ(FILPREV,*) (EPS(IB),IB=1,NOBS)
CLOSE(FILPREV)

!   GUARDA OS VALORES ORIGINAIS ANTES DE INICIAR A ITERACAO
ALLOCATE (QCELAT(NC),QMAT(NC+1),PMSUPAT(NC+1),PMSSUAT(NC+1),PMSUBAT(NC+1))
ALLOCATE (QJAT(NC),VRSUPAT(NC), VRSSUAT(NC), VRSUBAT(NC),QRIOINIAT(NC,NTRMAX+1))
!ALLOCATE (SSSUAT(NC,NU),SRADAT(NC,NU),SSUBAT(NC,NU))
ALLOCATE (QSUPAT(NC),QSSUAT(NC),QSUBAT(NC))

QCELAT=QCEL2 ! ULTIMA VAZAO NA CELULA
QMAT=QM2 ! ULTIMA VAZAO DE MONTANTE CALCULADA 
PMSUPAT=PMSUP ! PROPORCAO DE FLUXO SUPERFICIAL
PMSSUAT=PMSSU ! PROPORCAO DE FLUXO SUBSEPERFICIAL
PMSUBAT=PMSUB ! PROPORCAO DE FLUXO SUBTERRANEO    
QJAT=QJ2 ! ULTIMA VAZAO DE JUSANTE CALCULADA
VRSUPAT=VRSUP ! VOLUME NO RIO DEVIDO AO FLUXO SUPERFICIAL NO INICIO DO INTERVALO
VRSSUAT=VRSSU ! VOLUME NO RIO DEVIDO AO FLUXO SUBSUPERFICIAL NO INICIO DO INTERVALO
VRSUBAT=VRSUB ! VOLUME NO RIO DEVIDO AO FLUXO SUBTERRANEO NO INICIO DO INTERVALO
QRIOINIAT=QRIOINI ! VAZAO DA CONDICAO INICIAL DE MUSKINGUM CUNGE EM CADA SUBTRECHO DA CELULA
SSSUAT=SSSU ! ARMAZENAMENTO SUBSUPERFICIAL
SRADAT=SRAD ! ARMAZENAMENTO RADICULAR
SSUBAT=SSUB ! ARMAZENAMENTO SUBTERRANEO
QSUPAT=QSUP ! FLUXO SUPERFICIAL
QSSUAT=QSSU ! FLUXO SUBSUPERFICIAL
QSUBAT=QSUB ! FLUXO SUBTERRANEO    
F1=0. ! FATOR DE CORRECAO
F2=0.
ITER=0
DIF1=0.
DIF2=0.

DO WHILE (ITER < 15)
    NBAC=0 ! INDICA O NUMERO DE SUBBACIAS A SEREM CORRIGIDAS
    F3=0.
    DO IB=1,NOBS
        IF(POSTORIO(IB) == 0) CYCLE ! POSTORIO INDICA QUE POSTOS SERAO USADOS PARA CORRIGIR VAZAO NA BACIA IB, 0 NAO CORRIGE
        IF(QOBS(POSTORIO(IB),IT) < 0.) CYCLE ! NAO EXISTE DADO OBSERVADO
        QR(POSTORIO(IB),IT)=QJ2(IQOBS(POSTORIO(IB)))
        DIF2(IB)=(QR(POSTORIO(IB),IT)-QOBS(POSTORIO(IB),IT))/(QOBS(POSTORIO(IB),IT)+0.001)
        
!        write(*,*) iter,ib,QR(POSTORIO(IB),IT),QOBS(POSTORIO(IB),IT),DIF2(IB)
        
        IF(ABS(DIF2(IB)) < EPS(IB)) CYCLE ! NAO CORRIGE POIS O ERRO EH MENOR QUE A TOLERANCIA
        NBAC=NBAC+1 ! NUMERO DE SUBBACIAS A SEREM CORRIGIDAS
                
!        IF(ITER > 2) THEN ! TEM PELO MENOS 2 PONTOS CALCULADOS, APLICA A SECANTE   
!            F3(IB)=F2(IB)-DIF2(IB)*(F2(IB)-F1(IB))/(DIF2(IB)-DIF1(IB))
!        ELSE ! APLICA UMA APROXIMACAO PROPORCIONAL
            F3(IB)=QOBS(POSTORIO(IB),IT)/(QR(POSTORIO(IB),IT)+0.001)
!        ENDIF        
!        write(*,*) iter,IB,f1(ib),f2(ib),f3(ib)
        
    ENDDO ! FIM LOOP BACIAS
    
    DO IC=1,NC
        IB=IBAC(IC)
        IF(F3(IB) /= 0.) THEN ! APLICA A CORRECAO SOMENTE NAS SUBBACIA IB ONDE O ERRO FOR GRANDE
            ! ATUALIZA ARMAZENAMENTO SUPERFICIAL, SUBSUPERFICIAL E SUBTERRANEA NA CELULA
!            DO IU=1,NU
!   	        SSSUAT(IC,IU) = SSSUAT(IC,IU)*F3(IB)
!   	        SRADAT(IC,IU) = SRADAT(IC,IU)*F3(IB) 
!               SSUBAT(IC,IU) = SSUBAT(IC,IU)*F3(IB)	            
!           ENDDO
            ! ATUALIZA A VAZAO SUPERFICIAL, SUBSUPERFICIAL E SUBTERRANEA NA CELULA
            QSUPAT(IC)=QSUPAT(IC)*F3(IB)
            QSSUAT(IC)=QSSUAT(IC)*F3(IB)
            QSUBAT(IC)=QSUBAT(IC)*F3(IB)
            QMAT(IC)=QMAT(IC)*F3(IB)
            QJAT(IC)=QJAT(IC)*F3(IB)
            QRIOINIAT(IC,1:NTRMAX+1)=QRIOINIAT(IC,1:NTRMAX+1)*F3(IB)
            ! CORRIGE OS VOLUMES NO CANAL
            VT = VRSUPAT(IC)+VRSSUAT(IC)+VRSUBAT(IC)
            VAUX = (1.-1/F3(IB))*DTP*(PMSUPAT(IC)*QMAT(IC)-VRSUPAT(IC)*QJAT(IC)/VT)
            VRSUPAT(IC) = MAX(VRSUPAT(IC)+VAUX,0.)
            VAUX = (1.-1/F3(IB))*DTP*(PMSSUAT(IC)*QMAT(IC)-VRSSUAT(IC)*QJAT(IC)/VT)
            VRSSUAT(IC) = MAX(VRSSUAT(IC)+VAUX,0.)
            VAUX = (1.-1/F3(IB))*DTP*(PMSUBAT(IC)*QMAT(IC)-VRSUBAT(IC)*QJAT(IC)/VT)
            VRSUBAT(IC) = MAX(VRSUBAT(IC)+VAUX,0.)
        
        ENDIF
    ENDDO
    
    ! PAUSE
    
    IF(NBAC == 0) EXIT ! NENHUMA SUBBACIA PRECISANDO CORRECAO

    ITER = ITER + 1    
    ! NO INICIO DO INTERVALO DE TEMPO ADOTA OS VALORES ATUALIZADOS
!   SSSU = SSSUAT
!   SRAD = SRADAT
    SSUB = SSUBAT
    QSUP = QSUPAT
    QSSU = QSSUAT
    QSUB = QSUBAT
    ! ATUALIZA OS VOLUMES SUPERFICIAL, SUBSUPERFICIAL, E SUBTERRANEO
    VSUP(1:NC)=QSUP(1:NC)*DTP*TKS(1:NC)/(1-TKS(1:NC))
    VSSU(1:NC)=QSSU(1:NC)*DTP*TKS(1:NC)/(1-TKS(1:NC))
    VSUB(1:NC)=QSUB(1:NC)*DTP*TKB(1:NC)/(1-TKB(1:NC))
    ! ATUALIZA COM OS VALORES DE VAZOESZ DO INCIO DO INTERVALO
    QM2=QMAT
    QJ2=QJAT
    PMSUP=PMSUPAT
    PMSSU=PMSSUAT
    PMSUB=PMSUBAT
    VRSUP=VRSUPAT
    VRSSU=VRSSUAT
    VRSUB=VRSUBAT
    QRIOINI=QRIOINIAT
    CALL CELULA
    CALL REDE ! PROPAGA
    ! SUBSTITUI AS VAZOES CALCULADAS
    DO IB=1,NOBS
        ! AQUI VER O QEU FAZER NA VERSAO HIDRODINAMICO
        QR(IB,IT)=QJ2(IQOBS(IB)) !QR(IB,IT) VAI SER COMPARADO A QOBS(IB,IT)
        F1(IB)=F2(IB)
        F2(IB)=F3(IB)
        DIF1(IB)=DIF2(IB)
    ENDDO
ENDDO

DEALLOCATE (QCELAT,QMAT,PMSUPAT,PMSSUAT,PMSUBAT,QJAT,QRIOINIAT) ! VAZOES NA REDE ANTERIORES 
DEALLOCATE (VRSUPAT,VRSSUAT,VRSUBAT) ! VOLUMES ARMAZENADOS NO RIO ANTERIORES
DEALLOCATE (SSSUAT,SRADAT,SSUBAT)
DEALLOCATE (QSUPAT,QSSUAT,QSUBAT)
	
76  FORMAT(A100)
RETURN
END
