SUBROUTINE CELULA
!esta subrotina comanda o loop das celulas
USE VARS_MAIN
IMPLICIT NONE
INTEGER IC,IC2,IU,IB,IFP,K
REAL VBX,VIX,VSX !,PPU,FNA
INTEGER JULDAY

!VERIFICA A QUE MES CORRESPONDE O DIA JULIANO
IF(CALENDAR .EQ. 360) then
    CALL CALDAT360(JDIA,IMES,IDIA,IANO)
ELSE
    CALL CALDAT366(JDIA,IMES,IDIA,IANO)
ENDIF

JDIA=JDIA-JULDAY(1,1,IANO,CALENDAR)+1

DO IC2=1,NCDOM	 	!LOOP NAS CELULAS DO DOMINIO
    IC=ICDOM(IC2)
	IB=IBAC(IC)

    DSUP=DSUPALL(IC,IT)
    DSS=0.
    DSUB=DSUBALL(IC,IT)

	VSUB(IC)=VSUB(IC)+DSUB*ACEL(IC)*1000000
	VSSU(IC)=VSSU(IC)+DSS*ACEL(IC)*1000000
	VSUP(IC)=VSUP(IC)+DSUP*ACEL(IC)*1000000

	!CALCULA VAZOES DAS CELULAS USANDO O RLS
	VBX=VSUB(IC)*TKB(IC)
	QSUB(IC)=(VSUB(IC)-VBX)/DTP
	VSUB(IC)=VBX
	VIX=VSSU(IC)*TKS(IC)
	QSSU(IC)=(VSSU(IC)-VIX)/DTP
	VSSU(IC)=VIX
	VSX=VSUP(IC)*TKS(IC)
	QSUP(IC)=(VSUP(IC)-VSX)/DTP
	VSUP(IC)=VSX
	
    DSUPB(IB,IT)=DSUPB(IB,IT)+QSUP(IC)*(DTP/1000.)/(ACEL(IC)*KCB(IB)) !ESCOMENTO SUPERFICIAL DA BACIA EM MM NO DELTAT
    DSSUB(IB,IT)=DSSUB(IB,IT)+QSSU(IC)*(DTP/1000.)/(ACEL(IC)*KCB(IB)) !ESCOMENTO INTERMEDIÁRIO DA BACIA EM MM
    DSUBB(IB,IT)=DSUBB(IB,IT)+QSUB(IC)*(DTP/1000.)/(ACEL(IC)*KCB(IB)) !ESCOMENTO SUBTERRÂNEO DA BACIA	EM MM
ENDDO !FIM DO LOOP DAS CÉLULAS

RETURN
END
	
