!
!  ESTA funcao AJEITA OS DADOS E CHAMA O MODELO
!==================================================================
real*8 function functn(xpar)
USE VARS_MAIN
USE VARS_CALIB
implicit none
REAL*8 xpar(nopt)
REAL PAR(NPAR)
INTEGER  IU,I,IC,IC2,K,IAUX
!
!  ASSIGN x TO APPROPRIATE PARAMETERS IN MODEL
!
PAR=VPAR ! VETOR ORIGINAL DE PARAMETROS

do k = 1, nopt
    iaux=DEXP(xpar(k))*10000.
    par(pos(k))=float(iaux)/10000. ! LIMITA O VALOR DE PARA 4 DIGITOS SIGNIFICATIVOS
enddo

! KSAT CONDUTIVIDADE HIDRAULICA SATURADA (MM/H)
! B PARAMETRO DA CURVA DE RETENCAO
! PSIB PRESSAO DE ENTRADA DO AR (KPA)
! THS UMIDADE VOLUMETRICA NA SATURACAO
! THR UMIDADE VOLUMETRICA RESIDUAL     

!DO IU=1,NU
!    IF(SOLO(IU) /= 14) THEN
!        ! CALCULA OS PARAMETROS DE CADA SUB-BACIA
!        SSMAX(IBCAL,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*PAR(1) ! ARMAZENAMENTO MAXIMO CAMADA SUPERIOR DO SOLO
!        SRMAX(IBCAL,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*PAR(2) ! ARMAZENAMENTO MAXIMO EM MM NA SEGUNDA CAMADA
!        SMAX(IBCAL,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*PAR(3) ! ARMAZENAMENTO MAXIMO EM MM NA TERCEIRA CAMADA
!        ALPHA(IBCAL,IU)=ALPHA_REF*PAR(7) ! COEFICIENTE DE ANISOTROPIA
!        KSS(IBCAL,IU)=(KSAT(SOLO(IU))*24./1000.)*PAR(4) ! CONDUTIVIDADE HIDRAULICA SATURADA CAMADA SUPERIOR M/DIA
!        TSUB(IBCAL,IU)=TSUB_REF*PAR(5) ! TRANSMISSIVIDADE MAXIMA
!        MU(IBCAL,IU)=MU_REF*PAR(6) ! 
!        CSI(IBCAL,IU)=MIN(CSI_REF(IU)*PAR(8),1.) ! CAPACIDADE DE CAMPO           
!    ENDIF
!ENDDO

CS(IBCAL)=CS_REF*PAR(9)
CB(IBCAL)=CB_REF*PAR(10)*86400. ! CB EM DIAS FOI MULTIPLICADO POR 86400 PARA CB FICAR EM SEG
!
!

DO IC2=1,NCDOM
    IC=ICDOM(IC2)
    IF(IBAC(IC) == IBCAL) THEN ! CELULA QUE PERTENCE A BACIA SENDO OTIMIZADA
!        DO IU=1,NU
!	        LAMBDAM(IC,IU)=0.0  ! ATUALIZA O VALOR DE LAMBDAM
!		    IF(SMAX(IBCAL,IU).GT.0) THEN ! PULA AGUA
!		        DO K=2,50
!				    LAMBDAM(IC,IU)=LAMBDAM(IC,IU)+0.5*(LAMBDAI(IC,K)**(1./MU(IBCAL,IU))+LAMBDAI(IC,K-1)**(1./MU(IBCAL,IU)))*(AC(IC,K)-AC(IC,K-1))
!			    ENDDO
!			    LAMBDAM(IC,IU)=LAMBDAM(IC,IU)**MU(IBCAL,IU)
!		    ENDIF
!	    ENDDO
	    !ATUALIZA OS COEFICIENTES DO RLS 
   		TKB(IC)=EXP(-DTP/(CB(IBCAL)))	    !CB DEFINIDO EM SEGUNDOS EM LESOLO.F90
    	TKS(IC)=EXP(-DTP/(CS(IBCAL)*TCON(IC)))   !CS DEFINIDO EM LESOLO.F90	
	ENDIF
ENDDO

! CHAMA O MODELO
CALL MODELO
CALL FOBJ

IF(ISNAN(FOB) == .TRUE.) THEN ! CASO A COMBINACAO DE PARAMETROS GERE UM NAN
    FOB=1.
    FOB=HUGE(FOB) ! GERA UM NUMERO GRANDE
ENDIF

functn = FOB
return

end function functn