SUBROUTINE LEBACIA

USE VARS_MAIN
!USE VARS_CALIB ! ALOCA VALORES DE REFERENCIA DOS PARAMETROS DE SOLO PARA USAR NA CALIBRACAO
IMPLICIT NONE
INTEGER :: IB
REAL :: DCS,DCB

CS=0.
CB=0.

OPEN(FILBACIA,FILE=DIR_DADOS//'Entrada/ParBacia.hig',STATUS='OLD')
! LE PARAMETROS DE ESCOAMENTO IN-CELL DE CADA SUB-BACIA
READ(FILBACIA,72) TITULO
READ(FILBACIA,*) TSUB_REF
READ(FILBACIA,*) MU_REF
READ(FILBACIA,*) ALPHA_REF
READ(FILBACIA,*) CS_REF
READ(FILBACIA,*) BC1,BC2,BC3
READ(FILBACIA,*) QMESP
READ(FILBACIA,72) TITULO
READ(FILBACIA,73) (TITULO,CB(IB),QESP(IB),QCONS(IB),IB=1,NB)

CLOSE (FILBACIA)

OPEN(FILAJUSTE,FILE=DIR_DADOS//'Entrada/ParAjuste.hig',STATUS='OLD')
READ(FILAJUSTE,*) 
DO IB=1,NB

 	READ(FILAJUSTE,'(A10,80x,2G10.0)') TITULO,DCS,DCB
	CS(IB)=CS_REF*DCS
!	GAROFOLO - ALTERADO O CALCULO DO CB PARA RODAR SUBDIARIO
!    CB(IB)=CB(IB)*DCB*86400. ! CB CALCULADO EM DIAS E TRANSFORMADO A SEGUNDOS
    CB(IB)=CB(IB)*DCB*10800. ! CB CALCULADO EM DIAS E TRANSFORMADO A SEGUNDOS
ENDDO

CLOSE(FILAJUSTE)

72	FORMAT(A70)
73	FORMAT(A10,3G10.0)
RETURN
END
