SUBROUTINE LEFIX
USE VARS_MAIN
IMPLICIT NONE
INTEGER K,IDIAFIN,IMESFIN,IANOFIN,IHORAFIN,IDIAPRE,IMESPRE,IANOPRE,IHORAPRE,JUL,JULDAY

!esta subrotina le o arquivo PARFIX.hig onde estao os dados gerais fixos da simulaçao
!como o numero de celulas, o numero de usos do solo
!o numero de intervalos de tempo e de postos pluviometricos
OPEN(FILFIX,FILE=DIR_DADOS//'Entrada/ParFix.hig',STATUS='OLD')		!abre arquivo de dados gerais

READ(FILFIX,75) TITULO !LE CABECALHO PRINICPAL
WRITE(*,*) TITULO
READ(FILFIX,*) !LE LINHA EM BRANCO
READ(FILFIX,75) TITULO !LE TITULO DA APLICAÇÃO
READ(FILFIX,*)  !LE OUTRA LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
READ(FILFIX,71)IDIA,IMES,IANO,IHORAINI !LÊ DATA E HORA DO INÍCIO DA SIMULAÇÃO
WRITE(*,71)IDIA,IMES,IANO,IHORAINI
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO	
READ(FILFIX,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN !LÊ DATA E HORA DO FIM DA SIMULAÇÃO
WRITE(*,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN	
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO  
WRITE(*,72) TITULO	
READ(FILFIX,76) DTP					!LÊ INTERVALO DE TEMPO EM SEGUNDOS
WRITE(*,*) DTP
! CALCULA O NUMERO DE INTERVALOS DE TEMPO
JUL=(JULDAY(IMESFIN,IDIAFIN,IANOFIN)-JULDAY(IMES,IDIA,IANO))*86400+INT(DTP)+(IHORAFIN-IHORAINI)*3600
NT=JUL/INT(DTP)

READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
READ(FILFIX,'(I10,I10)')NC,NB	         		!LÊ NUMERO DE CÉLULAS, USOS, BACIAS
WRITE(*,71)NC,NB			           	!LÊ NUMERO DE CÉLULAS, USOS, BACIAS  
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO
ICALIB=0
READ(FILFIX,*)NOBS                  	!lê quantos postos com dados observados tem e qual o nome do arquivo dos dados
WRITE(*,*)NOBS 
NBVFO=NOBS
NHIDG=NOBS
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75)TITULO					!LE TEXTO
WRITE(*,72)TITULO
DO K=1,NHIDG
	READ(FILFIX,*)IHIDG(K)
	IQOBS(K)=IHIDG(K)
	WRITE(*,*)IHIDG(K)					!lê as células correspondentes aos pontos em que se deseja gravar os hidrogramas
ENDDO
CLOSE (FILFIX)

! FORMATOS
71	FORMAT(6I10)
72  FORMAT(1X,A100)
75	FORMAT(A100)
76	FORMAT(F10.0)
RETURN
END
