SUBROUTINE LEFIX
USE VARS_MAIN
IMPLICIT NONE
INTEGER K,IDIAPRE,IMESPRE,IANOPRE,IHORAPRE,JUL,JULDAY

!esta subrotina le o arquivo PARFIX.hig onde estao os dados gerais fixos da simula�ao
!como o numero de celulas, o numero de usos do solo
!o numero de intervalos de tempo e de postos pluviometricos
OPEN(FILFIX,FILE=DIR_DADOS//'Entrada/ParFix.hig',STATUS='OLD')		!abre arquivo de dados gerais

READ(FILFIX,75) TITULO !LE CABECALHO PRINICPAL
WRITE(*,*) TITULO
READ(FILFIX,*) !LE LINHA EM BRANCO
READ(FILFIX,75) TITULO !LE TITULO DA APLICA��O
READ(FILFIX,*)  !LE OUTRA LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
READ(FILFIX,71)IDIA,IMES,IANO,IHORAINI !L� DATA E HORA DO IN�CIO DA SIMULA��O
WRITE(*,71)IDIA,IMES,IANO,IHORAINI
READ(FILFIX,*)							!L� LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO	
READ(FILFIX,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN !L� DATA E HORA DO FIM DA SIMULA��O
WRITE(*,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN
READ(FILFIX,*)
READ(FILFIX,75) TITULO
WRITE(*,*) TITULO
READ(FILFIX,71) ICALIB
WRITE(*,*)"ICALIB", ICALIB
READ(FILFIX,*)
READ(FILFIX,*) TITULO
WRITE(*,*) TITULO
READ(FILFIX,*) CALENDAR
WRITE(*,*) CALENDAR
READ(FILFIX,*)							!L� LINHA EM BRANCO
READ(FILFIX,75) TITULO  
WRITE(*,72) TITULO	
READ(FILFIX,76) DTP					!L� INTERVALO DE TEMPO EM SEGUNDOS
WRITE(*,*) DTP
! CALCULA O NUMERO DE INTERVALOS DE TEMPO
JUL=(JULDAY(IMESFIN,IDIAFIN,IANOFIN,CALENDAR)-JULDAY(IMES,IDIA,IANO,CALENDAR))*86400+INT(DTP)+(IHORAFIN-IHORAINI)*3600
NT=JUL/INT(DTP)
IANOI = IANO
IMESI = IMES
IDIAI = IDIA
IHORAI = IHORAINI
READ(FILFIX,*)							!L� LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
READ(FILFIX,'(I10,I10)')NC,NB	         		!L� NUMERO DE C�LULAS, USOS, BACIAS
WRITE(*,71)NC,NB			           	!L� NUMERO DE C�LULAS, USOS, BACIAS  
READ(FILFIX,*)							!L� LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO
READ(FILFIX,*)NOBS, ARQOBS                  	!l� quantos postos com dados observados tem e qual o nome do arquivo dos dados
WRITE(*,*)NOBS , ARQOBS
NBVFO=NOBS
NHIDG=NOBS
READ(FILFIX,*)							!L� LINHA EM BRANCO
READ(FILFIX,75)TITULO					!LE TEXTO
WRITE(*,72)TITULO
DO K=1,NHIDG
	READ(FILFIX,*)IHIDG(K)
	IQOBS(K)=IHIDG(K)
	WRITE(*,*)IHIDG(K)					!l� as c�lulas correspondentes aos pontos em que se deseja gravar os hidrogramas
ENDDO
CLOSE (FILFIX)
!pause
! FORMATOS
71	FORMAT(6I10)
72  FORMAT(1X,A100)
75	FORMAT(A100)
76	FORMAT(F10.0)
RETURN
END
