SUBROUTINE LEFIX
USE VARS_MAIN
IMPLICIT NONE
INTEGER K,IDIAFIN,IMESFIN,IANOFIN,IHORAFIN,IDIAPRE,IMESPRE,IANOPRE,IHORAPRE,JUL,JULDAY

!esta subrotina le o arquivo PARFIX.hig onde estao os dados gerais fixos da simulaçao
!como o numero de celulas, o numero de usos do solo
!o numero de intervalos de tempo e de postos pluviometricos
OPEN(FILFIX,FILE=DIR_DADOS//'Entrada/ParFix.hig',STATUS='OLD')		!abre arquivo de dados gerais

READ(FILFIX,75) TITULO !LE CABECALHO PRINICPAL
WRITE(*,*) TITULO
READ(FILFIX,*) !LE LINHA EM BRANCO
READ(FILFIX,75) TITULO !LE TITULO DA APLICAÇÃO
READ(FILFIX,*)  !LE OUTRA LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
READ(FILFIX,71)IDIA,IMES,IANO,IHORAINI !LÊ DATA E HORA DO INÍCIO DA SIMULAÇÃO
WRITE(*,71)IDIA,IMES,IANO,IHORAINI
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO	
READ(FILFIX,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN !LÊ DATA E HORA DO FIM DA SIMULAÇÃO
WRITE(*,71)IDIAFIN,IMESFIN,IANOFIN,IHORAFIN	
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO  
WRITE(*,72) TITULO	
READ(FILFIX,76) DTP					!LÊ INTERVALO DE TEMPO EM SEGUNDOS
! CALCULA O NUMERO DE INTERVALOS DE TEMPO
JUL=(JULDAY(IMESFIN,IDIAFIN,IANOFIN)-JULDAY(IMES,IDIA,IANO))*86400+INT(DTP)+(IHORAFIN-IHORAINI)*3600
NT=JUL/INT(DTP)

READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO 
WRITE(*,72) TITULO
!READ(FILFIX,71)NC,NU,NB	         		!LÊ NUMERO DE CÉLULAS, USOS, BACIAS  
READ(FILFIX,'(I10,10X,I10)')NC,NB	         		!LÊ NUMERO DE CÉLULAS, USOS, BACIAS  
!WRITE(*,71)NC,NU,NB			           	!LÊ NUMERO DE CÉLULAS, USOS, BACIAS  
WRITE(*,71)NC,NB			           	!LÊ NUMERO DE CÉLULAS, USOS, BACIAS  
READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75) TITULO
WRITE(*,72) TITULO
READ(FILFIX,71) ICALIB					!LE OPCAO DE EXECUCAO
WRITE(*,71) ICALIB
IF(ICALIB == 2) THEN ! FAZ PREVISAO
    READ(FILFIX,*) ! LINHA EM BRANCO
	READ(FILFIX,75) TITULO
    WRITE(*,72) TITULO
    READ(FILFIX,71)IDIAPRE,IMESPRE,IANOPRE,IHORAPRE !LÊ DATA E HORA DO FIM DA PREVISAO
    WRITE(*,71)IDIAPRE,IMESPRE,IANOPRE,IHORAPRE	
    ! CALCULA ALCANCE DA PREVISAO EM INTERVALOS DE TEMPO
    JUL=(JULDAY(IMESPRE,IDIAPRE,IANOPRE)-JULDAY(IMESFIN,IDIAFIN,IANOFIN))*86400+(IHORAPRE-IHORAFIN)*3600
    NTPREV=JUL/INT(DTP) ! NUMERO DE INTERVALOS DE PREVISAO
    IF(NTPREV < 0) THEN
        WRITE(*,*) '*** DATA DE FIM DE SIMULACAO OU DE PREVISAO ERRADA(S)***'
        STOP
    ENDIF
ELSE
    NTPREV=0
    READ(FILFIX,*) ! LINHA EM BRANCO
    READ(FILFIX,*) ! LINHA EM BRANCO
    READ(FILFIX,*) ! LINHA EM BRANCO
ENDIF

!READ(FILFIX,*)							!LÊ LINHA EM BRANCO
!READ(FILFIX,75)TITULO
!WRITE(*,72)TITULO
!READ(FILFIX,71)NBVFO
!WRITE(*,71)NBVFO

READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75)TITULO					!LE TEXTO
WRITE(*,72)TITULO
READ(FILFIX,*)NOBS, ARQOBS				!lê quantos postos com dados observados tem e qual o nome do arquivo dos dados
WRITE(*,*)NOBS !,ARQOBS
NBVFO=NOBS
!READ(FILFIX,*)							!LÊ LINHA EM BRANCO
!READ(FILFIX,75)TITULO					!LE TEXTO
!WRITE(*,72)TITULO
!READ(FILFIX,*)(IQOBS(K),K=1,NOBS)		!Lê número da célula em que existem dados observados
!WRITE(*,*)(IQOBS(K),K=1,NOBS)

!READ(FILFIX,*)							!LÊ LINHA EM BRANCO
!READ(FILFIX,75)TITULO					!LE TEXTO
!WRITE(*,72)TITULO
!READ(FILFIX,*)NHIDG					!Lê em quantos pontos se deseja gravar o hidrograma
!WRITE(*,*)NHIDG

NHIDG=NOBS

READ(FILFIX,*)							!LÊ LINHA EM BRANCO
READ(FILFIX,75)TITULO					!LE TEXTO
WRITE(*,72)TITULO
DO K=1,NHIDG
	READ(FILFIX,*)IHIDG(K)
	IQOBS(K)=IHIDG(K)
	WRITE(*,*)IHIDG(K)					!lê as células correspondentes aos pontos em que se deseja gravar os hidrogramas
ENDDO
!
!READ(FILFIX,*) !LE LINHA EM BRANCO
!READ(FILFIX,75)TITULO !LE TITULO
!WRITE(*,72)TITULO
!READ(FILFIX,*) NMAPAS    !LE NUMERO DE MAPAS DE USO DA TERRA
!WRITE(*,*) NMAPAS
!
!READ(FILFIX,*)							!LE LINHA EM BRANCO
!READ(FILFIX,75) TITULO					!LE TITULO
!WRITE(*,72)TITULO
!READ(FILFIX,75) TITULO					!LE TITULO
!WRITE(*,*)TITULO
!DO K=1,NMAPAS
!	READ(FILFIX,'(2(I2,1X),I4,1X,A25)') IDIAFIN,IMESFIN,IANOFIN,ARQMAP(K) !LE DATA DO MAPA DE USO DA TERRA E SEU NOME
!	! DETERMINA O NUMERO DO INTERVALO DE TEMPO ONDE MUDA O MAPA DE USO DA TERRA
!	JUL = (JULDAY(IMESFIN,IDIAFIN,IANOFIN) - JULDAY(IMES,IDIA,IANO))*86400 + INT(DTP)
!	! SE A DATA INICIAL DA SIMULACAO OU PREVISAO FOR POSTERIOR A ULTIMA DATA DO USO DA TERRA, ITMAP<0 E VALE O ULTIMO MAPA LIDO
!	ITMAP(K) = JUL/INT(DTP) 
!	WRITE(*,'(2(I2,A),I4,2X,A25)') IDIAFIN,'/',IMESFIN,'/',IANOFIN,ARQMAP(K)
!ENDDO
!READ(FILFIX,*)
!READ(FILFIX,75)TITULO					!LE TEXTO
!WRITE(*,72)TITULO
!READ(FILFIX,*) NUMSUBST,ARQSUBST !Lê em quantos pontos se deseja SUBSITUIR a vazão calculada pela lida de arquivo
!WRITE(*,*) ARQSUBST
!READ(FILFIX,*)
!READ(FILFIX,75)TITULO					!LE TEXTO
!WRITE(*,72)TITULO
!IF(NUMSUBST > 0) THEN
!    WRITE(*,*)'NUMSUBST',NUMSUBST
!    DO K=1,NUMSUBST
!        READ(FILFIX,*)ISUBST(K) !LÊ as células cuja vazao calculada será substituída pela lida
!        WRITE(*,*)ISUBST(K)
!    ENDDO
!ENDIF
CLOSE (FILFIX)
71	FORMAT(6I10)
72  FORMAT(1X,A100)
73	FORMAT(F10.2)
74	FORMAT(A10)
75	FORMAT(A100)
76	FORMAT(F10.0)
77	FORMAT(A40)
78  FORMAT(A150)
RETURN
END
