    !PROGRAM MHD-FL
	!******************************************************************
	!*********MODELO HIDROLÓGICO DISTRIBUÍDO - ROUTING*****************
	!******************************************************************
	!*		    Baseado no modelo MGB do                              *
	!*			Instituto de Pesquisas Hidráulicas                    *
	!*          desenvolvido pelo INPE                                *
	!******************************************************************
	!USE PORTLIB !biblioteca para calcular o tempo de processamento
	USE VARS_MAIN !módulo que contém as variáveis principais
!	USE VARS_CALIB !módulo que contém as variáveis da calibração
	IMPLICIT NONE
	INTEGER JULDAY, K, IMC
	INTEGER:: TEMPOI(3)=0, TEMPOF(3)=0
	REAL:: TEMPOT

	!CALL ITIME(TEMPOI)  ! INICIA CONTAGEM DO TEMPO	
	
    ! DIRETORIO DE TRABALHO (ESPECIFICADO EM VARS_MAIN)
    WRITE(*,*) 'DIRETORIO DE TRABALHO'
    WRITE(*,*) DIR_DADOS
    
	!____________LEITURA DE ARQUIVOS PRINCIPAIS________________
	CALL LEFIX 	!SUBROTINA DE LEITURA DE PARAMETROS FIXOS
    
    CALL ALLOCA_VARS(0) !ALLOCA VARIÁVEIS PRINCIPAIS
    
	IDINI=JULDAY(IMES,IDIA,IANO) !CONVERTE O DIA DE INICIO EM CALENDARIO JULIANO
	
!   EXCLUIDO - MHD-ROUTING GAROFOLO
!	CALL LEVEG !SUBROTINA DE LEITURA DE PARAMETROS DA VEGETACAO (ALBEDO, iaf, RS E Z MENSAIS)
!	CALL LESOLO !SUBROTINA ASSOCIADA AOS PARAMETROS DE SOLO
    CALL LECELL !SUBROTINA DE LEITURA DO ARQUIVO DAS CELULAS	
!	CALL LEQOBS	!LEITURA DE DADOS DE VAZAO OBSERVADA
!   CALL LECLIMED !SUBROTINA DE LEITURA DO ARQUIVO DE DADOS CLIMATOLOGICOS MENSAIS
!   EXCLUIDO - MHD-ROUTING GAROFOLO
!	CALL LEMET ! LE OS DADOS METEROLOGICOS DE TODOS O PERIODO DE SIMULACAO
    CALL LEESC
    CALL LEBACIA
!	IF(NUMSUBST>0)THEN
!		CALL LESUBST
!	ENDIF
	!___________FIM DA LEITURA DOS ARQUIVOS PRINCIPAIS ______________

	!_______________PREPARACAO DE DADOS_____________________
	CALL PARCEL !CALCULA ALGUNS PARÂMETROS DAS CÉLULAS E DO RIO
	CALL PARCUNGE !CALCULA PARAMETROS PARA PROPAGACAO MUSKINGUM-CUNGE
!   EXCLUIDO - MHD-ROUTING GAROFOLO
	!CALL QQMET !VERIFICA A QUALIDADE DOS DADOS METEOROLOGICOS
	!____________FIM DA PREPARACAO DE DADOS_____________________
    
	!DECIDE SE VAI SIMULAR, CALIBRAR OU FAZER PREVISÃO (ICALIB=0; ICALIB=1; ICALIB=2) 
	!CALIBRA_CASE: SELECT CASE (ICALIB) !VERIFICA SE CALIBRA OU NÃO
	!CASE (0) ! NÃO CALIBRA, APENAS SIMULA
		WRITE(*,*)
		WRITE(*,*)' FAZENDO SIMULACAO'
		WRITE(*,*)
		CALL SIMULA	
	    CLOSE (FILSOL) !ARQUIVO DE SAIDA DADOS DO SOLO


	CALL ALLOCA_VARS(1) !DEALLOCA VARIÁVEIS PRINCIPAIS

	WRITE(*,*)'PROGRAMA TERMINOU'
	PAUSE
	STOP
	END
