SUBROUTINE PARCUNGE
!Esta rotina calcula o valor ideal de
!1- dtcal (intervalo de tempo de calculo da propagação)
!2- NTR (numero de subtrechos em que sera dividida a propagação)
USE VARS_MAIN
IMPLICIT NONE
INTEGER NTR,IC

!	REAL DQ,DA,CELTEMP,HMUP,BTOT,AMENOR,BINUN,PERIM,QPLAN,APLAN,RPLAN,QMENOR !VARIAVEL AUXILIAR
REAL COEF,DTCAL,DX      	!VARIAVEIS AUXILIARES	
REAL ALONG,HFLOW,DECLIV  	!VARIAVEIS AUXILIARES

RUGMAN=0.030 !COEFICIENTE DE MANNING É CONSIDERADO FIXO EM 0,03 PARA TODOS OS TRECHOS E RIOS
ICODMUSK=0 !POR PRINCIPIO CONSIDERA TODAS AS PROPAGACOES POR MUSKINGUN CUNGE LINEAR
DTCAL=MAX(DTP/24.,600.) ! (1 HORA DADOS DIARIOS, 10' DADOS HORARIOS)

DO IC=1,NC !LOOP DAS CÉLULAS

	IF(ACEL(IC)>0.1.AND.ADREN(IC)/ACEL(IC)>1.5)THEN ! CELULAS COM RIO
		COEF=1.67*DECL(IC)**0.3/RUGMAN**0.6
		CEL(IC)=COEF*(QREF(IC)/BRIO(IC))**0.4
		ALONG=SRIO(IC)*1000. !CONVERTE PARA METROS
		DX=0.5*CEL(IC)*DTCAL*(1+SQRT(1+3.068*QREF(IC)/(2.*DECL(IC)*BRIO(IC)*CEL(IC)*CEL(IC)*DTCAL)))
		NTR=NINT(ALONG/DX) !CALCULA NUMERO DE TRECHOS
		NTR=MAX(NTR,1)
				
		IF(NTR > NTRMAX)THEN 
			WRITE(*,*) 'NUMERO DE SUB-TRECHOS MAIOR QUE', NTRMAX,' NA ROTINA PARCUNGE!!!'
			STOP 'PAROU '
		ENDIF
		
		DT(IC)=DTCAL
		NTRC(IC)=NTR

	ELSE !AREAS FONTE (SINKS), SEM RIO, NAO INTERESSAM
		DT(IC)=0.0
		NTRC(IC)=0
	ENDIF

ENDDO !FIM DO LOOP DAS CÉLULAS

IF(NFP > 0) THEN ! EXISTEM CELULAS COM PLANICIE DE ALAGAMENTO	
    ! DEFINE O PASSO DE TEMPO PARA O CALCULO NA PLANICIE (HUNTER ET AL. 
    DX=SQRT(ACEL(ICELLFP(1))) ! DISTANCIA ENTRE CELULAS DA PLANICIE
    DECLIV=0.01/DX ! DECLIVIDADE MINIMA ENTRE CELULAS DE PLANICIE (ADMITINDO 1 CM NA DIFERENCA DE COTA ENTRE ELEMNTOS)
    HFLOW=2. ! MAXIMA COTA NO ELEMENTO DE PLANICIE EM METROS
    DTFP=DX**2/4.*(2*RUGMAN*DECLIV**0.5/HFLOW**1.667)
    DTFP=DTP
ENDIF

RETURN
END
