	MODULE VARS_MAIN
	!DECLARAÇÃO DE VARIÁVEIS DO PROGRAMA PRINCIPAL
	IMPLICIT NONE
	SAVE
	
	CHARACTER(*),PARAMETER:: DIR_DADOS = '/Users/hidrologia/Desktop/MHD-R_clean/dados_' !DIRETORIO DOS DADOS

	
	INTEGER,PARAMETER:: NTRMAX=20 !NUMERO MAXIMO DE SUBTRECHOS DE PROPAGACAO MUSKINGUM CUNGE
	INTEGER,PARAMETER:: NTMUP=20 !NUMERO DE PONTOS DA TABELA DO MUSKINGUN-CUNGE NAO LINEAR
    
	!NUMEROS 	 
	INTEGER NC,NCDOM !,NU ! NUMERO DE CELULAS, DE USOS, E DE CELULAS DO DOMINIO SIMULADO/CALIBRADO
	INTEGER NT !NUMERO DE INTERVALOS DE TEMPO
	INTEGER NSTEP ! NUMERO DE INTERVALOS DE TEMPO ATE O INICIO DA SIMULACAO (NSTEP>0, A SIMULACAO SE INICIA APOS O INICIO DAS OBSERVACOES) 	
	INTEGER NB !NUMERO DE BACIAS
	INTEGER NOBS,IQOBS(60) !NUMERO DE SERIES DE VAZAO OBSERVADA, numero das células com dados observados
	INTEGER NHIDG ,IHIDG(60) !NUMERO DE HIDROGRAMAS QUE SE DESEJA GRAVAR, NUMERO DAS CÉLULAS EM QUE SE DESEJA OS HIDROGRAMAS
 
	!CONTADORES
	INTEGER IT !INTERVALO DE TEMPO
	
	!-------VARIAVEIS COM NUMEROS DOS ARQUIVOS------------
	!ARQUIVOS DE ENTRADA
	INTEGER,PARAMETER:: FILFIX=1 !ARQUIVO DOS PARAMETROS FIXOS
	INTEGER,PARAMETER:: FILHIG=4 !ARQUIVO DAS CELULAS
	INTEGER,PARAMETER:: FILTOP=9 !ARQUIVO DE INDICES TOPOGRAFICOS NAS CELULAS
	INTEGER,PARAMETER:: FILAJUSTE=10 !ARQUIVO DOS FATORES DE PONDERACAO DOS PARAMETROS DE SOLO E DA BACIA
	INTEGER,PARAMETER:: FILBACIA=11 !ARQUIVO DOS PARAMETROS DE ESCOAMENTO DA BACIA
	INTEGER,PARAMETER:: FILSSUP=31 !ARQUIVO COM DADOS DE ESCOAMENTO SUPERFICIAL LIDO EM LeEsc.f90
	INTEGER,PARAMETER:: FILSSUB=32 !ARQUIVO COM DADOS DE ESCOAMENTO SUBTERRANEO LIDO EM LeEsc.f90

	!ARQUIVOS DE SAÍDA	
	INTEGER,PARAMETER:: FILHID=22 !ARQUIVO DOS HIDROGRAMAS DAS SUB-BACIAS
	INTEGER,PARAMETER:: FILPRP=23 !ARQUIVO DE HIDROGRAMA COM PROPORÇÕES
	INTEGER,PARAMETER:: FILBAC=25 !ARQUIVO DE SAIDA DE DADOS MEDIOS DAS BACIAS 
	INTEGER,PARAMETER:: FILSOL=26 !ARQUIVO DO SOLO (1 BLOCO)
	INTEGER,PARAMETER:: FILFP=30 !ARQUIVO CONTENDO INFORMACOES DA TOPOGRAFIA DO FLOODPLAIN
	!-----------------------------------------------------

	INTEGER ICALIB,INIAJU ! OPCAO DA RODADA, E NUMERO DE DELTATS ANTES INICIO DA COMPARAÇÃO CALCULADO X OBSERVADO (SPIN-UP)
	REAL,ALLOCATABLE:: QR(:,:) !VAZÃO NOS EXUTORIOS DAS BACIAS
	INTEGER,ALLOCATABLE:: KCB(:)!NUMERO DE CELULAS EM CADA SUB-BACIA 

	!VALORES MEDIOS POR SUB-BACIA
	REAL,ALLOCATABLE:: DSUPB(:,:),DSSUB(:,:),DSUBB(:,:)
	REAL,ALLOCATABLE:: QBSUB(:),QBSSU(:),QBSUP(:)
	INTEGER IDIA,IMES,IANO,IHORA !DATA E DIA DO CALENDARIO 
	INTEGER IDINI ! DIA EM QUE SE INICIA A SIMULACAO
	INTEGER IHORAINI !HORA EEM QUE INICIA A SIMULAÇÃO NO DIA INICIAL 
	INTEGER JDIA !DIA DO CALENDÁRIO JULIANO
    INTEGER IDIAFIN,IMESFIN,IANOFIN,IHORAFIN
	CHARACTER*120 TITULO !VARIÁVEL ALFA PARA LER TÍTULOS DOS ARQUIVOS DE ENTRADA
	REAL DTP !INTERVALO DE TEMPO DE CÁLCULO PRINCIPAL (DADO EM SEGUNDOS NO ARQUIVO DE ENTRADA)
	CHARACTER CDATA*10 ! DATA EM FORMATO CHARACTER
	CHARACTER,ALLOCATABLE:: CDATAG(:)*10 ! ARQUIVO COM TODAS AS DATAS EM FORMATO CHARACTER PARA IMPRESSAO
	
	REAL,ALLOCATABLE:: QESP(:) !VAZÃO ESPECIFICA DE BASE (M3/S/KM2)
	REAL,ALLOCATABLE:: QCONS(:) !CONSUMO DE AGUA NA BACIA NO EXUTORIO (M3/S)
	
	!NUMERO DE SUBTRECHOS E INTERVALO DE TEMPO DE CALCULO MUSKINGUM-CUNGE
	INTEGER,ALLOCATABLE:: NTRC(:)
	REAL,ALLOCATABLE:: DT(:)
	REAL,ALLOCATABLE:: CEL(:),TKS(:),TKB(:) !CELERIDADE NO RIO E COEFICIENTES DO RLS DA CELULA

	!PARAMETROS RELACIONADOS AO SOLO
	REAL,ALLOCATABLE:: SMAX(:,:),KSS(:,:),TSUB(:,:),ALPHA(:,:),CSI(:,:),SSMAX(:,:),MU(:,:),SRMAX(:,:)
	REAL,ALLOCATABLE:: NETA(:),D1(:),D2(:),D3(:)
	REAL,ALLOCATABLE:: SSUB(:,:)!ARMAZENAMENTO NA CAMADA INFERIOR DO SOLO
	REAL,ALLOCATABLE:: SRAD(:,:) !ARMAZENAMENTO NA ZONA RADICULAR PROFUNDA
	REAL,ALLOCATABLE:: SECRBS(:) !PARAMETRO DE TRANSPIRACAO DE SOLO NU 
	REAL,ALLOCATABLE:: SECRJAH(:),SECRJAL(:) !PARAMETROS DE TRANSPIRACAO DE SOLO NU 	
	REAL,ALLOCATABLE:: TCON(:),CB(:),CS(:)!PARAMETROS DA PROPAGAÇÃO NA CÉLULA

	INTEGER,ALLOCATABLE:: IEXUT(:)!INDICA CELULA DO EXUTORIO DA BACIA
	REAL,ALLOCATABLE:: BRIO(:)!LARGURA DO RIO
	INTEGER,ALLOCATABLE:: ICELL(:),IBAC(:),CELJUS(:),ICDOM(:) !BACIA,CELULA DE JUSANTE, CELULA DO DOMINIO SIMULADO/CALIBRADO
	REAL,ALLOCATABLE:: XCEL(:),YCEL(:)!COORDENADAS DO CENTRO DA CELULA
	REAL,ALLOCATABLE:: HCEL(:),LCEL(:),ACEL(:),ADREN(:),SRIO(:),DECL(:) !HMAX, HMIN, E ÁREA DA CÉLULA, AREA DRENADA EM CELULAS, COMPRIMENTO DO RIO E DECLIVIDADE DO RIO
	INTEGER,ALLOCATABLE:: IDREN(:) !VETOR QUE ORDENA OS VALORES DE AREA DE DRENAGEM EM ORDEM CRESCENTE PARA A ROTINA REDE
	REAL,ALLOCATABLE:: PUSO(:,:) 	!PROPORCAO DE USOS NA CELULA
	REAL,ALLOCATABLE::AC(:,:),LAMBDAI(:,:),TANB(:) !INDICES TOPOGRAFICOS E HISTOGRAMA NA CELULA
	REAL,ALLOCATABLE:: QREF(:) !VAZAO DE REFERENCIA
	REAL QMESP,BC1,BC2,BC3 ! VAZAO MEDIA ESPECIFICA DE TODA A BACIA E COEF DE CALCULO DA LARGURA DO RIO NA CELULA
    REAL MU_REF,CS_REF,ALPHA_REF,TSUB_REF,CB_REF
  
	!MONTECARLO
	INTEGER NBVFO ! NUMERO DA BACIA PARA A QUAL SE DESEJA IMPRIMIR AS FUNCOES OBJETIVO E OS VALORS MEDIOS DAS VARIAVEIS
	
	REAL,ALLOCATABLE:: QRG(:,:)	!ARMAZENA HIDROGRAMAS NAS CELULAS DESIGNADAS
	REAL,ALLOCATABLE:: QRB(:,:)	!ARMAZENA HIDROGRAMAS NOS EXUTÓRIOS DAS SUB-BACIAS
	REAL,ALLOCATABLE:: QM1(:),QJ1(:),QM2(:),QJ2(:) !VAZOES A MONTANTE E A JUSANTE NA CÉLULA i NO TEMPO 1 E 2
	REAL,ALLOCATABLE:: QCEL1(:),QCEL2(:) !VAZÕES ORIGINADAS NA CELULA NOS INSTANTES t E t+1 NA CÉLULA i
	REAL,ALLOCATABLE:: PMSUB(:),PMSSU(:),PMSUP(:),PJSUB(:),PJSSU(:),PJSUP(:) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO
	REAL,ALLOCATABLE:: VRSUB(:),VRSSU(:),VRSUP(:) !VOLUMES DAS PROPORÇÕES NO TRECHO
	REAL,ALLOCATABLE:: QSUB(:),QSSU(:),QSUP(:)		!VAZAO NA CELULA
	REAL,ALLOCATABLE:: VSUB(:),VSSU(:),VSUP(:)		!VOLUME NA CELULA

	REAL,PARAMETER:: PI=3.141592 !pi
	REAL,PARAMETER:: STEFAN=4.903E-9 !CONSTANTE DE STEFAN BOLSTZMANN EM MJ M-2 K-4 D-1
	REAL E0,E0AG ! EVAPORACAO POTENCIAL DE AGUA INTERCEPTADA E DE UMA SUPERFICIE DE AGUA LIVRE
	REAL GAMMA ! CONSTANTE PSICOMETRICA	EM KPA/C (EQ. 4.2.28)
	REAL DELTA ! DECLIVIDADE DA CURVA DE PRESSAO DE VAPOR (EQ. 4.2.3)
	REAL RA ! RESISTENCIA AERODICAMICA DA VEGETACAO E DA AGUA
	REAL,ALLOCATABLE:: EVQ(:) !EVAPORAÇÃO DIRETA DAS SUPERFÍCIES LÍQUIDAS (BLOCO ÁGUA) DA CÉLULA EM M3/S

	REAL,ALLOCATABLE:: QCONTORM(:,:),QCONTORJ(:,:) !VAZÃO CONDICAO DE CONTORNO DE MONTANTE E JUSANTE DE CADA CELULA EM CADA DT DE MC 
	REAL,ALLOCATABLE:: QRIOINI(:,:) !VAZÃO DA CONDICAO INICIAL DE MUSKINGUM CUNGE EM CADA SUBTRECHO DA CELULA
	REAL,ALLOCATABLE:: BPLAN(:) !LARGURA DA PLANÍCIE DE INUNDAÇÃO (INCLUI O PROPRIO RIO)
	REAL,ALLOCATABLE:: HCALHA1(:),HCALHA2(:) !PROF EM QUE INICIA E EM QUE A PLANICIE ESTA TOT INUNDADA
	REAL,ALLOCATABLE:: QMUP(:,:),AMUP(:,:),BMUP(:,:),CMUP(:,:) !TABELA MUSKINGUN NAO LINEAR
	
	REAL,ALLOCATABLE:: ZFPT(:,:),AFPT(:,:),VFPT(:,:) ! TABELAS DE COTA, AREA ALAGADA E VOLUME PARA CELULAS DE PLANICIE
	REAL,ALLOCATABLE:: ZFP(:),AFP(:),VFP(:) ! COTA DA ÁGUA NA PLANICIE, AREA ALAGADA E VOLUME PARA CELULAS DE PLANICIE
	REAL,ALLOCATABLE:: ZFPB(:),ZVERT(:) ! COTA DE FUNDO DA CELULA DE PLANICIE, ALTURA DE VERTIMENTO
	INTEGER,ALLOCATABLE:: ICELLFP(:),CELLN(:),CELLW(:) ! CELULAS DE PLANICIE E CELULAS ADJACENTES A UMA CELULA DE PLANICIE AO NORTE E OESTE
	REAL,ALLOCATABLE:: QRFP(:) ! VAZAO DE TROCA ENTRE A PLANICIE E O RIO
	REAL CVA,BVA,CVL,BVL,FCH ! COEFICIENTE E LARGURA DE VERTEDOR AFOGADO E DE VERTEDOR LIVRE, CONDUTANCIA HIDRAULICA DA PLANICIE 
	INTEGER NFP ! NUMERO DE CELULAS QUE COMPOEM A PLANICIE
	
	INTEGER,ALLOCATABLE:: ICODMUSK(:) !CODIGO QUE INDICA SE É LINEAR (0) OU NAO LINEAR (1)
    !MODIFICAÇÃO - MHD-ROUTING GAROFOLO
	REAL DSUP ! ESCOAMENTO SUPERFICIAL
	REAL,ALLOCATABLE:: DSUPALL(:,:) ! ESCOAMENTO SUPERFICIAL
	REAL DD   ! DRENAGEM PROFUNDA
	REAL DSS  ! DRENAGEM SUPSUPERFICIAL
	REAL,ALLOCATABLE:: DSUBALL(:,:) ! ESCOAMENTO BASE
	REAL DSUB ! ESCOAMENTO BASE
	REAL:: RUGMAN=0.030 !COEFICIENTE DE MANNING É CONSIDERADO FIXO EM 0,03 PARA TODOS OS TRECHOS E RIOS
	REAL DTFP ! PASSO DE TEMPO PARA O MODELO DE PLANICIE
	
	!VARIAVEIS INTERNAS
	REAL F

    !VARIAVEIS QMEDIAS
    INTEGER :: IANOI,IDIAI,IMESI,IHORAI, CALENDAR
	
    REAL,ALLOCATABLE:: NASH(:),LNASH(:),R2(:),ERRV(:),ERRE(:),R2L(:) !COEF. NASH, ERRO NOS VOLUMES, COEF NASH LOGARITMOS

	CHARACTER (7) ATEMPO
	REAL DECLX

	END MODULE
