        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:48 2016
        MODULE ALLOCA_VARS__genmod
          INTERFACE 
            SUBROUTINE ALLOCA_VARS(IOP)
              INTEGER(KIND=4) :: IOP
            END SUBROUTINE ALLOCA_VARS
          END INTERFACE 
        END MODULE ALLOCA_VARS__genmod
