        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 12 11:48:56 2016
        MODULE CALIBRA__genmod
          INTERFACE 
            SUBROUTINE CALIBRA
            END SUBROUTINE CALIBRA
          END INTERFACE 
        END MODULE CALIBRA__genmod
