        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:16 2016
        MODULE CALIBRA__genmod
          INTERFACE 
            SUBROUTINE CALIBRA
            END SUBROUTINE CALIBRA
          END INTERFACE 
        END MODULE CALIBRA__genmod
