        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:34 2016
        MODULE CELULA__genmod
          INTERFACE 
            SUBROUTINE CELULA
            END SUBROUTINE CELULA
          END INTERFACE 
        END MODULE CELULA__genmod
