        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:12 2016
        MODULE ESCOAMENTOS__genmod
          INTERFACE 
            SUBROUTINE ESCOAMENTOS(IC,IU,IB)
              INTEGER(KIND=4) :: IC
              INTEGER(KIND=4) :: IU
              INTEGER(KIND=4) :: IB
            END SUBROUTINE ESCOAMENTOS
          END INTERFACE 
        END MODULE ESCOAMENTOS__genmod
