        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:16 2016
        MODULE FUNCTN__genmod
          INTERFACE 
            FUNCTION FUNCTN(XPAR) RESULT(FUNCTN_0)
              USE VARS_CALIB
              REAL(KIND=8) :: XPAR(NOPT)
              REAL(KIND=8) :: FUNCTN_0
            END FUNCTION FUNCTN
          END INTERFACE 
        END MODULE FUNCTN__genmod
