        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:27:06 2016
        MODULE INTERPMUSK__genmod
          INTERFACE 
            SUBROUTINE INTERPMUSK(QMUSKNL,CELMUSKNL,BMUSKNL,IC)
              REAL(KIND=4) :: QMUSKNL
              REAL(KIND=4) :: CELMUSKNL
              REAL(KIND=4) :: BMUSKNL
              INTEGER(KIND=4) :: IC
            END SUBROUTINE INTERPMUSK
          END INTERFACE 
        END MODULE INTERPMUSK__genmod
