        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:37 2016
        MODULE LEBACIA__genmod
          INTERFACE 
            SUBROUTINE LEBACIA
            END SUBROUTINE LEBACIA
          END INTERFACE 
        END MODULE LEBACIA__genmod
