        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:55 2016
        MODULE LECELL__genmod
          INTERFACE 
            SUBROUTINE LECELL
              USE VARS_MAIN
            END SUBROUTINE LECELL
          END INTERFACE 
        END MODULE LECELL__genmod
