        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:14 2016
        MODULE LECLIMED__genmod
          INTERFACE 
            SUBROUTINE LECLIMED
            END SUBROUTINE LECLIMED
          END INTERFACE 
        END MODULE LECLIMED__genmod
