        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 12 11:48:38 2016
        MODULE LESUBST__genmod
          INTERFACE 
            SUBROUTINE LESUBST
            END SUBROUTINE LESUBST
          END INTERFACE 
        END MODULE LESUBST__genmod
