        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:19 2016
        MODULE LESUBST__genmod
          INTERFACE 
            SUBROUTINE LESUBST
            END SUBROUTINE LESUBST
          END INTERFACE 
        END MODULE LESUBST__genmod
