        !COMPILER-GENERATED INTERFACE MODULE: Mon Aug 15 22:28:59 2016
        MODULE LEUSO__genmod
          INTERFACE 
            SUBROUTINE LEUSO(IMAPAS)
              INTEGER(KIND=4) :: IMAPAS
            END SUBROUTINE LEUSO
          END INTERFACE 
        END MODULE LEUSO__genmod
