        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:00 2016
        MODULE LEUSO__genmod
          INTERFACE 
            SUBROUTINE LEUSO(IMAPAS)
              INTEGER(KIND=4) :: IMAPAS
            END SUBROUTINE LEUSO
          END INTERFACE 
        END MODULE LEUSO__genmod
