        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:06 2016
        MODULE LEVEG__genmod
          INTERFACE 
            SUBROUTINE LEVEG
            END SUBROUTINE LEVEG
          END INTERFACE 
        END MODULE LEVEG__genmod
