        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 13:44:19 2016
        MODULE MODELO__genmod
          INTERFACE 
            SUBROUTINE MODELO
            END SUBROUTINE MODELO
          END INTERFACE 
        END MODULE MODELO__genmod
