        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:01 2016
        MODULE MONTECARLO__genmod
          INTERFACE 
            SUBROUTINE MONTECARLO
            END SUBROUTINE MONTECARLO
          END INTERFACE 
        END MODULE MONTECARLO__genmod
