        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 12 11:48:33 2016
        MODULE MONTECARLO__genmod
          INTERFACE 
            SUBROUTINE MONTECARLO
            END SUBROUTINE MONTECARLO
          END INTERFACE 
        END MODULE MONTECARLO__genmod
