        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:39 2016
        MODULE PARCUNGE__genmod
          INTERFACE 
            SUBROUTINE PARCUNGE
            END SUBROUTINE PARCUNGE
          END INTERFACE 
        END MODULE PARCUNGE__genmod
