        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:27:02 2016
        MODULE PREVISAO__genmod
          INTERFACE 
            SUBROUTINE PREVISAO
            END SUBROUTINE PREVISAO
          END INTERFACE 
        END MODULE PREVISAO__genmod
