        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:57:10 2016
        MODULE PREVISAO__genmod
          INTERFACE 
            SUBROUTINE PREVISAO
            END SUBROUTINE PREVISAO
          END INTERFACE 
        END MODULE PREVISAO__genmod
