        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 12 11:49:12 2016
        MODULE PREVISAO__genmod
          INTERFACE 
            SUBROUTINE PREVISAO
            END SUBROUTINE PREVISAO
          END INTERFACE 
        END MODULE PREVISAO__genmod
