        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 25 11:26:43 2016
        MODULE REDEINI__genmod
          INTERFACE 
            SUBROUTINE REDEINI
            END SUBROUTINE REDEINI
          END INTERFACE 
        END MODULE REDEINI__genmod
