        !COMPILER-GENERATED INTERFACE MODULE: Fri Aug 12 11:48:56 2016
        MODULE SCEUA__genmod
          INTERFACE 
            SUBROUTINE SCEUA(FILEVOL)
              USE VARS_CALIB
              INTEGER(KIND=4) :: FILEVOL
            END SUBROUTINE SCEUA
          END INTERFACE 
        END MODULE SCEUA__genmod
