        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 17 09:56:58 2016
        MODULE TRANSPIRACAO__genmod
          INTERFACE 
            SUBROUTINE TRANSPIRACAO(IC,IU,IB)
              INTEGER(KIND=4) :: IC
              INTEGER(KIND=4) :: IU
              INTEGER(KIND=4) :: IB
            END SUBROUTINE TRANSPIRACAO
          END INTERFACE 
        END MODULE TRANSPIRACAO__genmod
