        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:57 2019
        MODULE ALLOCA_VARS__genmod
          INTERFACE 
            SUBROUTINE ALLOCA_VARS(IOP)
              INTEGER(KIND=4) :: IOP
            END SUBROUTINE ALLOCA_VARS
          END INTERFACE 
        END MODULE ALLOCA_VARS__genmod
