        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:50 2019
        MODULE ATUALIZA__genmod
          INTERFACE 
            SUBROUTINE ATUALIZA
              USE VARS_MAIN
            END SUBROUTINE ATUALIZA
          END INTERFACE 
        END MODULE ATUALIZA__genmod
