        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:53 2019
        MODULE BALANCO__genmod
          INTERFACE 
            SUBROUTINE BALANCO
            END SUBROUTINE BALANCO
          END INTERFACE 
        END MODULE BALANCO__genmod
