        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:53 2019
        MODULE DOMINIOBACIA__genmod
          INTERFACE 
            SUBROUTINE DOMINIOBACIA(IBCAL)
              INTEGER(KIND=4) :: IBCAL
            END SUBROUTINE DOMINIOBACIA
          END INTERFACE 
        END MODULE DOMINIOBACIA__genmod
