        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:57 2019
        MODULE LEBACIA__genmod
          INTERFACE 
            SUBROUTINE LEBACIA
            END SUBROUTINE LEBACIA
          END INTERFACE 
        END MODULE LEBACIA__genmod
