        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:55 2019
        MODULE LECELL__genmod
          INTERFACE 
            SUBROUTINE LECELL
              USE VARS_MAIN
            END SUBROUTINE LECELL
          END INTERFACE 
        END MODULE LECELL__genmod
