        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:55 2019
        MODULE LEESC__genmod
          INTERFACE 
            SUBROUTINE LEESC
              USE VARS_MAIN
            END SUBROUTINE LEESC
          END INTERFACE 
        END MODULE LEESC__genmod
