        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:57 2019
        MODULE LEFIX__genmod
          INTERFACE 
            SUBROUTINE LEFIX
            END SUBROUTINE LEFIX
          END INTERFACE 
        END MODULE LEFIX__genmod
