        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:58 2019
        MODULE LEQOBS__genmod
          INTERFACE 
            SUBROUTINE LEQOBS
            END SUBROUTINE LEQOBS
          END INTERFACE 
        END MODULE LEQOBS__genmod
