        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:56 2019
        MODULE PARCEL__genmod
          INTERFACE 
            SUBROUTINE PARCEL
            END SUBROUTINE PARCEL
          END INTERFACE 
        END MODULE PARCEL__genmod
