        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:56 2019
        MODULE PARCUNGE__genmod
          INTERFACE 
            SUBROUTINE PARCUNGE
            END SUBROUTINE PARCUNGE
          END INTERFACE 
        END MODULE PARCUNGE__genmod
