        !COMPILER-GENERATED INTERFACE MODULE: Tue Jan 15 16:11:55 2019
        MODULE REDEINI__genmod
          INTERFACE 
            SUBROUTINE REDEINI
            END SUBROUTINE REDEINI
          END INTERFACE 
        END MODULE REDEINI__genmod
