SUBROUTINE ESCOAMENTOS(IC,IU,IB)
USE VARS_MAIN
IMPLICIT NONE
INTEGER IC,IU,IB,K
REAL SAUX,SFC,DSAUX,DELTAT,NMENOS,AUX,MUMENOS,CMAX,CI,CT,DSMAX,LAMBDAX
!	REAL AUX2
!	AUX2=SSUB(IC,IU)+SSSU(IC,IU)+srad(ic,iu)
!   WRITE(*,*) AUX2,pre(ic)


! VARIABLES DE ENTRADA
! PRE : PRECIPITACAO (mm)
! EC  : LAMINA INTERCEPTADA
! SSSU: ARMAZENAMENTO NA CAMADA SUPERIOR DO SOLO (mm)
! SSUB: ARMAZENAMENTO TOTAL (mm)

! PARAMETROS
! KSS : CONDUTIVIDADE HIDRAULICA DA CAMADA SUPERIOR DO SOLO (M/dia)
! TSUB : TRANSMISSIVIDADE PARA O PERFIL DO SOLO TOTALMENTE SATURADO (M2/dia)
! NETA : PARAMETRO NETA DE BROOKS COREY
! SMAX : ARMAZENAMENTO MEDIO NA CAMADA SUPERIOR DO SOLO (mm)
! AC(I) E LAMBDAI(I) HISTOGRAMA DO ÍNDICE TOPOGRÁFICO DA CELULA
! ALPHA: FATOR DE ANISOTROPIA PARA CONDUTIVIDADE HIDRÁULICA HORIZONTAL 
! CSI  : PERCENTUAL MINIMO DE ARMAZENAMENTO SUBTERRANEO PARA INÍCIO DO ESCOAMENTO BASE
! AC   : AREA DE CONTRIBUICAO MEDIA DA CELULA
! D1   : ESPESSURA HORIZONTE SUPERIOR DO SOLO
! D2   : ESPESSURA HORIZONTE INFERIOR DO SOLO 


!VARIAVEIS DE SAIDA
!DSUP : ESCOAMENTO SUPERFICIAL
!DSS  : ESCOAMENTO SUBSUPERFICIAL
!DSUB : ESCAOMENTO SUBTERRANEO
!DD   : DRENAGEM PROFUNDA
!SSUB : ARMAZENAMENTO DE TODO O PERFIL DO SOLO ATUALIZADO
!SSSU : ARMAZENAMENTO NA CAMADA SUPERIOR DO SOLO (ATUALIZADO)

!VARIAVEIS INTERNAS
!NMENOS : NETA -1
!AUX: AUXILIAR 
!ASAT: AREA SATURADA
!DELTAT	: INTERVALO DE TEMPO EM DIAS

DELTAT=DTP/86400.
NMENOS = NETA(IU) - 1
SFC=CSI(IB,IU)*SMAX(IB,IU)
DSMAX=SMAX(IB,IU)-SFC

! DETERMINA A AREA DE CONTRIBUICAO VARIAVEL USANDO O ARMAZENAMENTO SUBTERRANEO 
! DO INICIO DO INTERVALO
DSAUX=SSUB(IC,IU)-SFC
LAMBDAX=LAMBDAI(IC,1)	
IF(DSAUX > 0.) THEN
    AUX=LAMBDAM(IC,IU)*(DSMAX/DSAUX)**MU(IB,IU) 
	LAMBDAX=MIN(AUX,LAMBDAX)
ENDIF
IF(LAMBDAX >= LAMBDAI(IC,1)) THEN
	ASAT(IC,IU)=0.
ELSE
	ASAT(IC,IU)=1.
	DO K=2,49
		IF(LAMBDAX >= LAMBDAI(IC,K)) THEN
			ASAT(IC,IU)=AC(IC,K-1)+(LAMBDAX-LAMBDAI(IC,K-1))*(AC(IC,K)-AC(IC,K-1))/(LAMBDAI(IC,K)-LAMBDAI(IC,K-1))
			EXIT
		ENDIF
	ENDDO
ENDIF

! CALCULA FLUXO NAO SATURADO 
! ESTIMA O ARMAZENAMENTO PONDERADO NA PRIMEIRA CAMADA DE SOLO
! LAMINA DE AGUA QUE INFILTRA NA AREA NAO SATURADA = (1-ASAT)*(PRE-EC)
! ARMAZENAMENTO NA AREA SATURADA = ASAT*SSMAX 	
!!!!!!!!!SAUX=SSSU(IC,IU)+PRE(IC)-EC(IC,IU) ! LAMINA DE AGUA ACIMA DA REGIAO NAO SATURADA
! SE EC(IC,IU) < 0 - ORVALHO, PRE-EC > EC, E SOMA A PRECIPITACAO
SAUX=SSSU(IC,IU)+ASAT(IC,IU)*SSMAX(IB,IU)+(1-ASAT(IC,IU))*(PRE(IC)-EC(IC,IU))
IF(SAUX <= 0.) THEN
	SSSU(IC,IU) = 0.
	DSS = 0.
	DD = 0.
    DSUP=0.
ELSE
    IF(SAUX > SSMAX(IB,IU)) THEN
        ! ESCOAMENTO SUPERFICIAL POR SATURACAO FORA DA AREA DE CONTRIBUICAO VARIAVEL
	    DSUP=SAUX-SSMAX(IB,IU)
	    SAUX=SSMAX(IB,IU)
    ELSE
        DSUP=0.
    ENDIF
	AUX = (1+NMENOS*(1000*KSS(IB,IU)*DELTAT/SSMAX(IB,IU))*(LAMBDA(IC,IU)/LAMBDAN(IC,IU))*(SAUX/SSMAX(IB,IU))**NMENOS)**(1/NMENOS)
	SSSU(IC,IU)=SAUX/AUX
	! CALCULA A DRENAGEM TOTAL EM MM
	AUX=SAUX-SSSU(IC,IU)
	! CALCULA ESCOAMENTO SUBSUPERFICIAL
	DSS = MIN(AUX,ALPHA(IB,IU)*D1(IB)*TANB(IC)*AUX/LAMBDA(IC,IU))
	DD= AUX-DSS ! CALCULA A DRENAGEM PROFUNDA NO INTERVALO
	! SUBSTRAI O EFEITO DA AREA SATURADA PARA O CALCULO DA TRANSPIRACAO
    SSSU(IC,IU)=SSSU(IC,IU)-ASAT(IC,IU)*SSMAX(IB,IU) 
	IF(SSSU(IC,IU) < 0.) THEN
	    DD = DD + SSSU(IC,IU)
	    SSSU(IC,IU)=0.
	ENDIF
ENDIF

! TRANSFERE AGUA PARA A CAMADA 2
IF(D2(IB) > 0.) THEN
	SAUX=SRAD(IC,IU)+DD
    IF(SAUX > SRMAX(IB,IU)) THEN
        ! EXCESSO VOLTA PARA A CAMADA SUPERIOR
        SSSU(IC,IU) = SSSU(IC,IU) + SAUX - SRMAX(IB,IU) 
        IF(SSSU(IC,IU) > SSMAX(IB,IU)) THEN
            DSUP=DSUP+SSSU(IC,IU)-SSMAX(IB,IU)
		    SSSU(IC,IU)=SSMAX(IB,IU)
        ENDIF
        SAUX=SRMAX(IB,IU)
    ENDIF
    IF(SAUX <= 0.) THEN
        SRAD(IC,IU)=0.
        DD=0.
    ELSE
        AUX = (1+NMENOS*(1000*KSS(IB,IU)*DELTAT/SRMAX(IB,IU))*(SAUX/SRMAX(IB,IU))**NMENOS)**(1/NMENOS)
        SRAD(IC,IU)=SAUX/AUX
        DD = SAUX-SRAD(IC,IU) ! DRENAGEM PROFUNDA NO INTERVALO EM MM
    ENDIF
ENDIF

! CALCULA ESCOAMENTO SUPERFICIAL DO EXCESSO DA AREA NAO SATURADA E DA AREA 
! DE CONTRIBUICAO VARIAVEL
!DSUP=DSUP*(1-ASAT(IC,IU))+(PRE(IC)-EC(IC,IU))*ASAT(IC,IU) ESTAVA ERRADO
DSUP=DSUP+(PRE(IC)-EC(IC,IU))*ASAT(IC,IU)
DSAUX=DSAUX+DD ! ADICIONA A DRENAGEM PROFUNDA AO ARMAZENAMENTO SUBTERRANEO	
! CALCULA O ESCOAMENTO SUBTERRANEO
IF(DSAUX > 0.) THEN
	IF(MU(IB,IU).EQ.1.) THEN
		AUX=EXP(-1000*TSUB(IB,IU)*TANB(IC)*DELTAT/(DSMAX*LAMBDA(IC,IU)))
		SSUB(IC,IU)=DSAUX*AUX
	ELSE
		MUMENOS=MU(IB,IU)-1.
		AUX=1+MUMENOS*1000*TSUB(IB,IU)*TANB(IC)*DELTAT*(DSAUX/DSMAX)**MUMENOS/(LAMBDAM(IC,IU)*DSMAX)
        IF(AUX > 0) THEN
		    SSUB(IC,IU)=DSAUX/AUX**(1/MUMENOS)
		ELSE
		    SSUB(IC,IU)=0.
		ENDIF
	ENDIF
	DSUB = DSAUX-SSUB(IC,IU)
	SSUB(IC,IU) = SSUB(IC,IU) + SFC
ELSE
	SSUB(IC,IU) = DSAUX + SFC
	DSUB=0.
ENDIF
!    IF(IU==1 .AND. IC==1102) THEN
!	AUX2=srad(ic,iu)+SSUB(IC,IU)+SSSU(IC,IU)-PRE(IC)+EC(IC,IU)-AUX2+DSS+DSUP+DSUB
!    aux2=srad(ic,iu)+ssub(ic,iu)-aux2-dd+dsub
!    IF(ABS(AUX2) > 1.E-4) THEN
!    WRITE(*,*) SSSU(IC,IU),SSUB(IC,IU),srad(ic,iu),DSS,DD,DSUP,dsub,PRE(IC),ASAT(IC,IU)
!	WRITE(*,*) ' ',AUX2
!    PAUSE
!    ENDIF

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
RETURN
END