SUBROUTINE LEBACIA

USE VARS_MAIN
USE VARS_CALIB ! ALOCA VALORES DE REFERENCIA DOS PARAMETROS DE SOLO PARA USAR NA CALIBRACAO
IMPLICIT NONE
INTEGER :: IB
REAL :: DCS,DCB

CS=0.
CB=0.

OPEN(FILBACIA,FILE=DIR_DADOS//'Entrada/ParBacia.hig',STATUS='OLD')
! LE PARAMETROS DE ESCOAMENTO IN-CELL DE CADA SUB-BACIA
READ(FILBACIA,72) TITULO
READ(FILBACIA,*) TSUB_REF
READ(FILBACIA,*) MU_REF
READ(FILBACIA,*) ALPHA_REF
READ(FILBACIA,*) CS_REF
READ(FILBACIA,*) BC1,BC2,BC3
READ(FILBACIA,*) QMESP
READ(FILBACIA,72) TITULO
READ(FILBACIA,73) (TITULO,CB(IB),QESP(IB),QCONS(IB),IB=1,NB)

CLOSE (FILBACIA)

OPEN(FILAJUSTE,FILE=DIR_DADOS//'Entrada/ParAjuste.hig',STATUS='OLD')
READ(FILAJUSTE,*) 
DO IB=1,NB
    ! D2	:ESPESSURA DA SEGUNDA CAMADA DO SOLO
    ! D3    :ESPESSURA DA TERCEIRA CAMADA DO SOLO
    ! D1	:ESPESSURA DA CAMADA SUPERIOR DO SOLO
    ! DKSS	:FATOR DE PONDERACAO DO PARAMETRO KSS 
    ! DTSUB	:FATOR DE PONDERACAO DO PARAMETRO TSUB
    ! DMU	:FATOR DE PONDERACAO DO PARAMETRO TSUB
 	! cuidado aqui, verificar sempre a ordem de leitura dos paramentros    	
 	READ(FILAJUSTE,'(A10,80x,2G10.0)') TITULO,DCS,DCB
!    DO IU=1,NU
!        IF(SOLO(IU) /= 14) THEN
!            ! CALCULA OS PARAMETROS DE CADA SUB-BACIA
!            SSMAX(IB,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*D1(IB) ! ARMAZENAMENTO MAXIMO CAMADA SUPERIOR DO SOLO
!	        SRMAX(IB,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*D2(IB) ! ARMAZENAMENTO MAXIMO EM MM NA SEGUNDA CAMADA
!            SMAX(IB,IU)=(THS(SOLO(IU))-THR(SOLO(IU)))*1000*D3(IB) ! ARMAZENAMENTO MAXIMO EM MM NA TERCEIRA CAMADA
!            ALPHA(IB,IU)=ALPHA_REF*DALPHA ! COEFICIENTE DE ANISOTROPIA
!            KSS(IB,IU)=(KSAT(SOLO(IU))*24./1000.)*DKSS ! CONDUTIVIDADE HIDRAULICA SATURADA CAMADA SUPERIOR M/DIA
!            NETA(IU)=2.5+2.*B(SOLO(IU)) ! COEFICIENTE DA  CONDUTIVDADE HIDRAULICA NAO SATURADA
!            TSUB(IB,IU)=TSUB_REF*DTSUB ! TRANSMISSIVIDADE MAXIMA
!            MU(IB,IU)=MU_REF*DMU ! 
!	        CSI(IB,IU)=MIN(CSI_REF(IU)*DCSI,1.) ! CAPACIDADE DE CAMPO
!        ENDIF
!    ENDDO
	CS(IB)=CS_REF*DCS
!	GAROFOLO - ALTERADO O CALCULO DO CB PARA RODAR SUBDIARIO
!    CB(IB)=CB(IB)*DCB*86400. ! CB CALCULADO EM DIAS E TRANSFORMADO A SEGUNDOS
    CB(IB)=CB(IB)*DCB*10800. ! CB CALCULADO EM DIAS E TRANSFORMADO A SEGUNDOS
ENDDO

CLOSE(FILAJUSTE)

72	FORMAT(A70)
73	FORMAT(A10,3G10.0)
RETURN
END