SUBROUTINE LECELL
!esta subrotina le o arquivo cell.hig
!onde estao os dados das celulas e parametros topograficos
USE VARS_MAIN
IMPLICIT NONE
!VARIAVEIS QUE DEPENDEM DO NUMERO DE CELULAS----
INTEGER FLAGFP(NC) !INDICADOR 0 OU 1 DAS CELULAS QUE FAZEM PARTE DO FLOODPLAIN
INTEGER IBANT,IC,K,IB,IU,KB,IFP
REAL RES,XC,YC,DIST
LOGICAL EXISTE


OPEN(FILHIG,FILE=DIR_DADOS//'Entrada/cell_5km.hig',STATUS='OLD')
OPEN(FILTOP,FILE=DIR_DADOS//'Entrada/ParTop50000.hig',STATUS='OLD')
IBANT=1
IB=1
NFP=0
ICELL=0
DO IC=1,NC
	READ(FILHIG,*) K,XCEL(IC),YCEL(IC),IBAC(IC),ADREN(IC),ACEL(IC),HCEL(IC),LCEL(IC),SRIO(IC),DECL(IC),CELJUS(IC),FLAGFP(IC)
	!READ(FILHIG,'(I5,2G15.0,I5,2G10.0,2G5.0,G10.0,G10.0,2I5)') K,XCEL(IC),YCEL(IC),IBAC(IC),ADREN(IC),ACEL(IC),HCEL(IC),LCEL(IC),SRIO(IC),DECL(IC),CELJUS(IC),FLAGFP(IC)
    NFP=NFP+FLAGFP(IC)
!       LE DISTRIBUICAO DO INDICE TOPOGRÁFICO

	READ(FILTOP,'(45X,G10.0,50G10.0,50G20.0)') TANB(IC),(AC(IC,K),K=1,50),(LAMBDAI(IC,K),K=1,50)
	!DEFINE EXUTORIOS
	!verifica qual EH a celula que define o fim de uma sub-bacia
	IF(IBAC(IC) /= IBANT)THEN
		IEXUT(IB)=IC-1
		IBANT=IBAC(IC)
		IB=IB+1
	ENDIF
ENDDO

IEXUT(IB)=NC !O EXUTORIO DA ULTIMA SUB-BACIA É A ULTIMA CELULA
CELJUS(NC)=NC+1 ! A CELULA A JUSANTE DA ULTIMA SUBBACIA CORRESPONDE A CELULA NC+1

!*************************************************************
!VERIFICA O NUMERO DE CELULAS EM CADA SUB-BACIA
KCB(1)=IEXUT(1)
DO KB=2,NB
	KCB(KB)=IEXUT(KB)-IEXUT(KB-1)
ENDDO
!FIM DA VERIFICACAO DO NUMERO DE CELULAS EM CADA SUB-BACIA

!   CALCULA OS VALORES MEDIOS DE LAMBDA E LAMBDAN
!LAMBDAM=0.
!LAMBDAN=0.
!LAMBDA=0.
!DO IC=1,NC
!	DO IU=1,NU
!		IF(SMAX(IBAC(IC),IU).GT.0) THEN ! PULA AGUA
!			DO K=2,50
!				LAMBDA(IC,IU)=LAMBDA(IC,IU)+0.5*(LAMBDAI(IC,K)+LAMBDAI(IC,K-1))*(AC(IC,K)-AC(IC,K-1))
!				LAMBDAM(IC,IU)=LAMBDAM(IC,IU)+0.5*(LAMBDAI(IC,K)**(1./MU(IBAC(IC),IU))+LAMBDAI(IC,K-1)**(1./MU(IBAC(IC),IU)))*(AC(IC,K)-AC(IC,K-1))
!				LAMBDAN(IC,IU)=LAMBDAN(IC,IU)+0.5*(LAMBDAI(IC,K)**(1./NETA(IU))+LAMBDAI(IC,K-1)**(1./NETA(IU)))*(AC(IC,K)-AC(IC,K-1))
!			ENDDO
!			LAMBDAM(IC,IU)=LAMBDAM(IC,IU)**MU(IBAC(IC),IU)				
!			LAMBDAN(IC,IU)=LAMBDAN(IC,IU)**NETA(IU)
!		ENDIF
!	ENDDO
!ENDDO

IF(NFP > 0) THEN ! EXISTEM CELULAS COM PLANICIE DE ALAGAMENTO
    ALLOCATE (ZFPT(NFP,50),AFPT(NFP,50),VFPT(NFP,50),ZFP(NFP),ZVERT(NFP),ZFPB(NFP))
    ALLOCATE (AFP(NFP),VFP(NFP),ICELLFP(NFP),CELLN(NFP),CELLW(NFP),QRFP(NFP))
    INQUIRE(FILE=DIR_DADOS//'FLOODPLAIN.HIG',EXIST=EXISTE)
	IF(.NOT. EXISTE)THEN ! VERIFICA EXISTENCIA DE ARQUIVO COM DADOS DA PLANICIE ALAGADA   
        STOP 'NAO EXISTE ARQUIVO COM DADOS TOPOGRAFICOS DA PLANICIE'
    ELSE
        OPEN(FILFP,FILE=DIR_DADOS//'FLOODPLAIN.HIG',STATUS='OLD')
    ENDIF
    READ(FILFP,*)
    READ(FILFP,*)
    READ(FILFP,'(2G10.0)') CVL,BVL ! COEFICIENTE E LARGURA DE VERTEDOR LIVRE
    READ(FILFP,'(2G10.0)') CVA,BVA ! COEFICIENTE E LARGURA DE VERTEDOR AFOGADO
    READ(FILFP,'(2G10.0)') FCH ! CONDUTANCIA HIDRAULICA DA PLANICIE DE ALAGAMENTO
    READ(FILFP,*)
    
    ! LE DADOS DA ALTURA, DA FRACAO DA CELULA ALAGADA E DO VOLUME ALAGADO
    DO IFP=1,NFP
        ! ICELLFP INDICA QUAIS CELULAS DO ARQUIVO CELL.HIG PERTENCEM A PLANICIE DE INUNDACAO
        ! ICELLFP(IFP) = X INDICA QUE A CELULA IFP DO ARQUIVO FLOODPLAIN.HIG CORRESPONDE A X-ESIMA CELULA DO ARQUIVO CELL.HIG
        READ(FILFP,'(I10,2G10.0)') ICELLFP(IFP),ZVERT(IFP),ZFPB(IFP)
        READ(FILFP,'(10X,50G10.0)') (ZFPT(IFP,K),K=1,50)
        READ(FILFP,'(10X,50G10.0)') (AFPT(IFP,K),K=1,50)
        READ(FILFP,'(10X,50G10.0)') (VFPT(IFP,K),K=1,50)
        ! ICELL INDICA A POSICAO DAS CELULAS DA PLANICIE DO ARQUIVO CELL.HIG NO ARQUIVO FLOODPLAIN.HIG
        ! SE ICELL(IC) = 0 A CELULA IC DE CELL.HIG NAO PERTENCE A PLANICIE
        ! SE ICELL(IC) = X > 0, A CELULA IC PERTENCE A PLANICIE E CORRESPONDE A X-ESIMA CELULA DO ARQUIVO FLOODPLAIN.HIG
        ICELL(ICELLFP(IFP))=IFP
    ENDDO
    CLOSE(FILFP)

    ! DETERMINA A CONECTIVIDADADE DA PLANICIE USANDO AS COORDENADAS DA CELULA
    CELLN=0 !CELULA DA PLANICIE LOCALIZADA AO NORTE DA CELULA ANALISADA
    CELLW=0 !CELULA DA PLANICIE LOCALIZADA AO OESTE DA CELULA ANALISADA

    ! DETERMINA A RESOLUCAO DO MODELO PROCURANDO AS MINIMAS DISTANCIAS ENTRE CELULAS CONTIGUAS NO MEIO DO DOMINIO
    RES=9999.
    DO IC=1,10
        DIST=ABS(XCEL(NC/2+IC)-XCEL(NC/2+2*IC))
        IF(DIST /= 0) RES=MIN(RES,DIST)
    ENDDO

    DO IFP=1,NFP
        ! TESTA AO NORTE
        XC=XCEL(ICELLFP(IFP))
        YC=YCEL(ICELLFP(IFP))+RES
        DO K=1,NFP
            DIST=(XC-XCEL(ICELLFP(K)))**2.+(YC-YCEL(ICELLFP(K)))**2.
            IF(DIST < 0.01) THEN
                CELLN(IFP)=K
                EXIT
            ENDIF
        ENDDO
        ! TESTA AO OESTE
        XC=XCEL(ICELLFP(IFP))-RES
        YC=YCEL(ICELLFP(IFP))
        DO K=1,NFP
            DIST=(XC-XCEL(ICELLFP(K)))**2.+(YC-YCEL(ICELLFP(K)))**2.
            IF(DIST < 0.01) THEN
                CELLW(IFP)=K
                EXIT
            ENDIF
        ENDDO
    ENDDO
ENDIF

CLOSE (FILHIG)
CLOSE (FILTOP)
RETURN
END
