SUBROUTINE LECLIMED
!SUBROTINA QUE LÊ OS DADOS MEDIOS MENSAIS DE VARIAVEIS CLIMATICAS EM CADA CELULA
USE VARS_MAIN
IMPLICIT NONE
INTEGER I,J,IREC

OPEN(FILMED,FILE=DIR_DADOS//'ENTRADA'//ACLIMED,STATUS='OLD',RECL=NC,FORM='UNFORMATTED',ACCESS='DIRECT')

IREC=0
DO I =1, 12
	IREC=IREC+1
	!temperatura media (graus C)
    READ(FILMED,REC=IREC)(TAMM(I,J),J=1,NC)
	IREC=IREC+1
	!PONTO DE ORVALHO (GRAUS C)
    READ(FILMED,REC=IREC)(TDEWMM(I,J),J=1,NC)
	IREC=IREC+1
	! VELOCIDADE DO VENTO M/S
    READ(FILMED,REC=IREC)(VVMM(I,J),J=1,NC)
	IREC=IREC+1
	! RADIACAO GLOBAL DE ONDA CURTA INCIDENTE
    READ(FILMED,REC=IREC)(ROCMM(I,J),J=1,NC)
	IREC=IREC+1
	! PRESSAO ATMOSFERICA EM MB
    READ(FILMED,REC=IREC)(PRMM(I,J),J=1,NC)
ENDDO
CLOSE(FILMED)

RETURN
END