SUBROUTINE LEMC
!ESTA SUBROTINA É CHAMADA PARA LER AS INFORMACOES DOS EXP DE MONTECARLO
USE VARS_MAIN
USE VARS_CALIB
IMPLICIT NONE

   		
OPEN(FILMCPAR,FILE=DIR_DADOS//'PARMC.HIG', STATUS = 'OLD')


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!ARQUIVO COM OS DADOS PARA O MONTE CARLO		!
!												!
!!NUMERO DE PARAMETROS DE USOS					!
!7												!
!												!
!!NUMERO DE EXPERIMENTOS						!
!2												!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

READ(FILMCPAR,*) TITULO
WRITE(*,*)TITULO
READ(FILMCPAR,*)
READ(FILMCPAR,*) TITULO
WRITE(*,*)TITULO
READ(FILMCPAR,*) NPARUSO

READ(FILMCPAR,*)
READ(FILMCPAR,*) TITULO
WRITE(*,*)TITULO
READ(FILMCPAR,*) NEXP

CLOSE(FILMCPAR)
MCREC = (NU-1)*NPARUSO+4 !NAO CONSIDERA A AGUA CUIDADO!!!! 

RETURN
END