SUBROUTINE LEMETPREV
!esta subrotina le os arquivos DE PREVISÃO DE CHUVA
!onde estao os dados de chuva para cada célula do modelo	
USE VARS_MAIN
IMPLICIT NONE
INTEGER IC

! ABRE ARQUIVO DE DADOS DE CHUVA PREVISTA
! FORMATO DO ARQUIVO = PREPREV_DDMMYYYYHH.BIN

OPEN(FILPLUPREV,FILE=DIR_DADOS//'PREVISAO/PREPREV_'//CDATAG(IT)//'.BIN',STATUS='OLD',FORM='UNFORMATTED',RECORDTYPE='STREAM') 
READ(FILPLUPREV)(PRE(IC),IC=1,NC)
CLOSE(FILPLUPREV)

!LE DADOS METEOROLOGICOS PREVISTOS PARA CALCULAR EVAPORACAO (APENAS PARA DADOS DIARIOS)
!FORMATO DO ARQUIVO = METDDMMYYYYHH.BIN
!	IF(IHORA /= 0) RETURN

OPEN(FILMETPREV,FILE=DIR_DADOS//'PREVISAO/METPREV_'//CDATAG(IT)//'.BIN', STATUS='OLD',FORM='UNFORMATTED',RECORDTYPE='STREAM') !dados METEOROLOGICOS interpolados
READ(FILMETPREV)(TA(IC),IC=1,NC) ! TEMPERATURA DO AR
READ(FILMETPREV)(TDEW(IC),IC=1,NC) ! TEMPERATURA PONTO DE ORVALHO
READ(FILMETPREV)(VV(IC),IC=1,NC) ! VELOCIDADE DO VENTO
READ(FILMETPREV)(PATM(IC),IC=1,NC) ! PRESSAO ATMOSFERICA
READ(FILMETPREV)(ROC(IC),IC=1,NC) ! RADIACAO GLOBAL INCIDENTE
CLOSE(FILMETPREV) !ARQUIVO DE DADOS METEOROLOGICOS PREVISTOS	

RETURN
END