	SUBROUTINE LEQOBS
	!SUBROTINA QUE LÊ DADOS OBSERVADOS DE VAZÃO
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER K,JULDAY,JUL,IDIA1,IMES1,IANO1,IHORA1,IAUX
	! DIA JULIANO INICIO SIMULACAO

	OPEN(FILOBS,FILE=DIR_DADOS//'Entrada/'//ARQOBS,STATUS='OLD')
	READ(FILOBS,71) TITULO
	! LE PRIMEIRO REGISTRO E EXTRAI A DATA, QUE DEVE ESTAR EM FORMATO DD/MM/AAAAHH
	READ(FILOBS,71) TITULO
	IAUX=INDEX(TITULO,'/') ! IDENTIFICA A PRIMEIRA BARRA DA DATA
	READ(TITULO(IAUX-2:IAUX-1),'(I2)') IDIA1 
    READ(TITULO(IAUX+1:IAUX+2),'(I2)') IMES1
    READ(TITULO(IAUX+4:IAUX+7),'(I4)') IANO1
    IF(TITULO(IAUX+8:IAUX+9) == '  ') THEN ! DATA NAO INCLUI HORA
        IHORA1=0
        IAUX=IAUX+7
    ELSE ! DATA INCLUI HORA
        READ(TITULO(IAUX+8:IAUX+9),'(I2)') IHORA1
	    IAUX=IAUX+9
	ENDIF
	BACKSPACE(FILOBS)
    ! CALCULA O NUMERO DE INTERVALOS DE TEMPO ATE O REGISTRO CORRESPONDENTE AO PRIMEIRO DIA DA SIMULACAO
    ! ATENCAO!!!! EH NECESSARIO QUE A DATA DE INICIO DAS OBSERVACOES NOS ARQUIVOS QOBS.PRN, PREC,BIN E MET.BIN SEJAM AS MESMAS
    NSTEP=(JULDAY(IMES,IDIA,IANO)-JULDAY(IMES1,IDIA1,IANO1))*86400+(IHORAINI-IHORA1)*3600
    NSTEP=NSTEP/INT(DTP)
    
	IF(NSTEP < 0) THEN ! OS DADOS METEOROLOGICOS SE INICIAM APOS O PERIODO DE SIMULACAO
	    WRITE(*,*) ' ***INICIO DA SIMULACAO ANTERIOR AO INICIO DOS DADOS DISPONIVEIS*** '
	    STOP 
	ELSE
	    ! SE NSTEP FOR MAIOR QUE ZERO DESPREZA OS PRIMEIROS NSTEP VALORES
	    DO IT=1,NSTEP
	        READ(FILOBS,*)
	    ENDDO
	ENDIF
	! LE O RESTANTE DO ARQUIVO
	write(*,*) NT/8
	DO IT=1,NT
		READ(FILOBS,'(A<IAUX>,1x,<NOBS>G10.0)') TITULO(1:IAUX),(QOBS(K,IT),K=1,NOBS)
	ENDDO
	WRITE(*,*)
	WRITE(*,'(A20,/,A<IAUX>,<NOBS>F10.3)') ' ULTIMA VAZAO LIDA  ',TITULO(1:IAUX),(QOBS(K,NT),K=1,NOBS)
	WRITE(*,*)
	CLOSE (FILOBS)
71	FORMAT(A80)
	!FIM DA LEITURA DE DADOS DE VAZAO OBSERVADA --------------------!

	RETURN
	END
