SUBROUTINE LEUSO(IMAPAS)
!esta subrotina le USO DO SOLO 
!PARA CADA CELULA, LE PERCENTAGEM DE CADA USO
USE VARS_MAIN
IMPLICIT NONE
INTEGER IC,IU,IMAPAS,IAUX
REAL AUX

OPEN(FILUSO,FILE=DIR_DADOS//'Entrada/'//ARQMAP(IMAPAS),STATUS='OLD')
!write(*,*)DIR_DADOS//ARQMAP(IMAPAS)
DO IC =1,NC
	READ(FILUSO,*) IAUX,AUX,AUX,IAUX,(PUSO(IC,IU),IU=1,NU)
	!READ(FILUSO,77) (PUSO(IC,K),K=1,NU)
ENDDO
!77	FORMAT(40X,30G5.0)
CLOSE(FILUSO)

!	WRITE(*,*)
!   WRITE(*,'(A28,1X,A15)')' LEU MAPA DE USOS DA TERRA: ', ARQMAP(IMAPAS)
!	WRITE(*,*)

RETURN
END
