SUBROUTINE LEVEG
!esta subrotina le o arquivo em que estao os dados DE VEGETACAO; 
! ATENCAO AGORA SAO DADOS MENSAIS DE 16 TIPOS DE VEGETACAO
!ALBEDO E IAF, variaveis mensalmente, para cada uso
USE VARS_MAIN
USE VARS_CALIB ! ALOCA VALORES DE REFERENCIA DOS PARAMETROS SOLO PARA USAR NA CALIBRACAO
IMPLICIT NONE 
REAL,ALLOCATABLE:: AUX(:,:) ! VARIAVEL AUXILIAR DE LEITURA DOS PARAMETROS DE VEGETACAO
INTEGER IU,IM,IVEG,NVEG
CHARACTER*5 MES(12)

ALLOCATE(VEG(NU+1),SOLO(NU+1)) ! ALLOCA TIPO DE VEGETACAO E TIPO DE SOLO
OPEN(FILBLOC,FILE=DIR_DADOS//'Entrada/Blocos.hig',STATUS='OLD')
! LE BLOCOS DA BACIA
READ(FILBLOC,72) TITULO
READ(FILBLOC,72) TITULO
READ(FILBLOC,*) (SOLO(IU),VEG(IU),IU=1,NU)
CLOSE(FILBLOC)
OPEN(FILVEG,FILE=DIR_DADOS//'Entrada/ParVeg_geral.hig',STATUS='OLD')
READ(FILVEG,71) TITULO
! LE PARAMETROS DE ESTRESSE DO MODELO DO JARVIS
READ(FILVEG,71) TITULO
READ(FILVEG,*) OMEGAC ! FATOR DE COMPENSACAO DE JARVIS
READ(FILVEG,*) FR ! FATOR DE DISTRIBUICAO DE RAIZES
READ(FILVEG,*) NVEG ! NUMERO DE TIPOS FUNCIONAIS DE VEGETACAO
ALLOCATE(AUX(NVEG,12)) 
VEG(NU+1)=NVEG ! RESERVA O USO NU + 1 PARA EVAPORACAO DE AREA ALAGADA 
! COMPATIBILIZA O TIPO DE VEGETACAO COM O TIPO DE SOLO PARA AGUA
DO IU=1,NU+1
    IF(VEG(IU) == NVEG) SOLO(IU)=14 ! SOLO CORRESPONDENTE A AGUA
ENDDO
!LE PARAMETROS AERODINAMICOS DA COBERTURA E ALOCA NOS DIFERENTES USOS
!ULTIMA COBERTURA SEMPRE AGUA
! OS PARAMETROS DE AGUA SEMPRE NO FINAL DO ARQUIVO PARVEG.HIG
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    ALB(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO
!LE INDICE DE AREA FOLIAR
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    IAF(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO
!LE ZVEG (ALTURA MÉDIA DA VEGETAÇÃO)
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    ZVEG(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO
!LE PERCENTAGEM DE COBERTURA DA VEGETACAO - COVER 
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    COVER(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO
!LE PRAD (PROFUNDIDADE RADICULAR)
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    PRAD(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO    
!LE DVEG - PLANO DE DESLOCAMENTO ZERO (M)
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    DVEG(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO
!LE RUGOSIDADE Z0 (M) 
READ(FILVEG,71) TITULO
READ(FILVEG,73) TITULO,(MES(IM),IM=1,12)
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,(AUX(IVEG,IM),IM=1,12)
ENDDO
DO IU=1,NU+1
    DO IM=1,12
	    Z0(IU,IM)=AUX(VEG(IU),IM)
	ENDDO
ENDDO   
!LE RC (RESISTÊNCIA SUPERFICIAL MINIMA DA VEGETAÇÃO)
READ(FILVEG,71) TITULO
DO IVEG=1,NVEG
	READ(FILVEG,'(A3,G8.0)') TITULO,AUX(IVEG,1)
ENDDO
DO IU=1,NU+1
	RC(IU)=AUX(VEG(IU),1)
ENDDO
!LE SCMAX (CAPACIDADE MAXIMA DO DOSSEL)
READ(FILVEG,71) TITULO
DO IVEG=1,NVEG
	READ(FILVEG,75) TITULO,AUX(IVEG,1)
ENDDO
DO IU=1,NU+1
    SCMAX(IU)=AUX(VEG(IU),1)
ENDDO
CLOSE(FILVEG)
DEALLOCATE(AUX)
71	FORMAT(A8)
72	FORMAT(A8,12G8.0)
73	FORMAT(A8,12A8)
74	FORMAT(A8,12G8.0)
75  FORMAT(A3,12G8.0)
RETURN
END
