SUBROUTINE MODELO
!Esta subrotina comanda o loop do tempo do modelo hidrológico e chama as 
!rotinas de balanco e propagação nas células e de propagação na rede de drenagem
USE VARS_MAIN
IMPLICIT NONE 
INTEGER,ALLOCATABLE:: NAUX(:) ! NUMERO DE SUBTRECHOS NO ARQUIVO DE CONDICOES INICIAIS 
REAL,ALLOCATABLE:: QAUX(:,:) ! VAZOES QRIOINI NO ARQUIVO DE CONDICOES INICIAIS 
INTEGER IMAPAS,IC,IC2,IB,IU,ITR1,ITR2 !CONTADORES
INTEGER JC,JU,IS,K 
REAL TEMPO ! TEMPO DE SIMULACAO EM DIAS
REAL SOMAD,SOMAAR,PMEDDIA
LOGICAL EXISTE
REAL VBX,AUX,DX ! 

! CONDICAO INICIAL USO DA TERRA
! ITMAP INDICA O NUMERO DO INTERVALO DE TEMPO ONDE MUDA O MAPA DE USO DA TERRA
! SE A DATA INICIAL DA PREVISAO FOR POSTERIOR A ULTIMA DATA DO USO DA TERRA, ITMAP < 0

! EXCLUIDO - MHD-ROUTING GAROFOLO
!IF(ITMAP(NMAPAS) <= 0) THEN
!    ! FORCA A LEITURA DO ULTIMO MAPA DE USO DA TERRA
!    CALL LEUSO(NMAPAS)
!ELSE
!    ! PROCURA O PRIMEIRO MAPA DE SOLO APOS INICIO DA SIMULACAO 
!	DO IMAPAS=1,NMAPAS
!		IF(ITMAP(IMAPAS) >= 0)THEN
!			CALL LEUSO(IMAPAS)
!            EXIT
!		ENDIF
!	ENDDO
!ENDIF

!ZERA EVAPORACAO E AREA SATURADA
! EXCLUIDO - MHD-ROUTING GAROFOLO
!ETT=0.0
!EC=0.0
!ETP=0.0
ASAT=0.0
! CONDICAO INICIAL DE ARMAZENAMENTO DO SISTEMA: CORRESPONDE A DATA INICIAL -1
! CRIA DATA PARA A CONDICAO INICIAL
TEMPO=IHORAINI/24.-DTP/86400
IF(TEMPO < 0) THEN
    TEMPO=TEMPO+1.
	JDIA=IDINI+INT(TEMPO)-1 ! DIA JULIANO DO CALENDÁRIO
ELSE
	JDIA=IDINI+INT(TEMPO) ! DIA JULIANO DO CALENDÁRIO
ENDIF

IHORA=NINT((TEMPO-INT(TEMPO))*24.) ! HORA DA SIMULACAO
CALL CALDAT(JDIA,IMES,IDIA,IANO)	
WRITE(CDATA(1:2),'(I2.2)') IDIA
WRITE(CDATA(3:4),'(I2.2)') IMES
WRITE(CDATA(5:8),'(I4)') IANO    
WRITE(CDATA(9:10),'(I2.2)') IHORA

!**********CONDIÇÕES INICIAIS*********************************************	        
! VERIFICA SE EXISTE ARQUIVO COM CONDICAO INICIAL	
INQUIRE(FILE=DIR_DADOS//'CCINI_'//CDATA//'.BIN',EXIST=EXISTE)
IF(.NOT. EXISTE) THEN ! CONDIÇÕES INICIAIS ESTIMADAS JA QUE NAO EXISTE ARQUIVO INICIAL
	DO IC2=1,NCDOM
	    IC=ICDOM(IC2)
	    IB=IBAC(IC)
	    ! DO PERFIL DE SOLO
	    !CONSIDERA QUE SOLO ESTA NA CAPACIDADE DE CAMPO NO INÍCIO DA SIMULAÇÃO NAS DUAS CAMADAS
!	    SSSU(IC,1:NU)=0.4*SSMAX(IB,1:NU)
!	    SSUB(IC,1:NU)=0.5*SMAX(IB,1:NU)
	    ! PARA DEFINIR A CAPACIDADE INICIAL DA ZONA RADICULAR USA O A ESPESSURA DA TERCEIRA CAMADA
!	    SRAD(IC,1:NU)=0.3*SRMAX(IB,1:NU)
        ! DOS RESERVATORIOS SUBTERRANEO, SUBSUPERFICIAL E SUPERFICIAL
	    VSUB(IC)=QESP(IB)*ACEL(IC)*CB(IB) ! CB EM SEGUNDOS
	    VBX=VSUB(IC)*EXP(-DTP/TKB(IC))

	    QSUB(IC)=(VSUB(IC)-VBX)/DTP

	    VSSU(IC)=0.0
	    VSUP(IC)=0.0
		QSUP(IC)=0.0
		QSSU(IC)=0.0
	ENDDO

    ! DA PLANICIE DE ALAGAMENTO
	IF(NFP > 0) THEN ! PLANICIE DE ALAGAMENTO SECA
	    AFP=0.0
	    VFP=0.0
	    ZFP=ZFPB
	    QRFP=0.0
	ENDIF
	!DA REDE DE DRENAGEM
	CALL REDEINI
	!GAROFOLO - MHD ROUTING COMENTADO POR NÃO HAVER TEMPERATURA
	!DE TEMPERATURA
!	TA=28.0
	INIAJU=720 ! SPIN-UP: INICIA A COMPARACAO OBSERVADO X CALCULADO DOIS ANO APOS
ELSE ! CONDIÇÕES INICIAIS DADAS PELOS VALORES ARMAZENADOS DO SOLO E NA REDE
    WRITE(*,*) ' EXISTE CONDICAO INICIAL'
	OPEN(FILCCINI,FILE=DIR_DADOS//'CCINI_'//CDATA//'.BIN', STATUS='OLD',FORM='UNFORMATTED',RECORDTYPE='STREAM')
	ALLOCATE(NAUX(NC),QAUX(NC,NTRMAX+1))
!	READ(FILCCINI) ((SSSU(IC,IU),IU=1,NU),IC=1,NC)
!	READ(FILCCINI) ((SRAD(IC,IU),IU=1,NU),IC=1,NC)
!	READ(FILCCINI) ((SSUB(IC,IU),IU=1,NU),IC=1,NC)
	READ(FILCCINI) VSUP
	READ(FILCCINI) VSSU
	READ(FILCCINI) VSUB
!	READ(FILCCINI) TA
	READ(FILCCINI) QM2
	READ(FILCCINI) QJ2
	READ(FILCCINI) NAUX
	READ(FILCCINI) QAUX
	READ(FILCCINI) QCEL2
	READ(FILCCINI) PMSUB
	READ(FILCCINI) PMSSU
	READ(FILCCINI) PMSUP
    READ(FILCCINI) VRSUB
    READ(FILCCINI) VRSSU
    READ(FILCCINI) VRSUP
    IF(NFP>0) THEN
	    READ(FILCCINI) VFP
        READ(FILCCINI) AFP
        READ(FILCCINI) QRFP
        ZFP=ZFPB
    ENDIF
	CLOSE(FILCCINI)
	INIAJU=1 ! SEM SPIN-UP PARA INICIO DE COMPARACAO
	! VERIFICA SE HOUVE MUDANCAS NO  NUMERO DE SUBTRECHOS E INTERPOLA SE NECESARIO
	QRIOINI=QAUX
    DO IC=1,NC
        IF(NTRC(IC) /= NAUX(IC)) THEN ! MUDOU O NUMERO DE SUBTRECHOS
            AUX=(NAUX(IC)+1)/(NTRC(IC)+1)
            DO ITR1=2,NTRC(IC)+1
                DX=(ITR1-1)*AUX+1
                DO ITR2=2,NAUX(IT)+1
                    IF(DX <= ITR2) THEN
                        QRIOINI(IC,ITR1)=QAUX(IC,ITR2)+(DX-ITR2)*(QAUX(IC,ITR2)-QAUX(IC,ITR2-1))
                        EXIT
                    ENDIF
                ENDDO
            ENDDO
        ENDIF
    ENDDO
    DEALLOCATE(NAUX,QAUX)
ENDIF
!****************************FIM DAS CONDIÇÕES INICIAIS*********************************
!	INICIO DO LOOP DO TEMPO. 
!GAROFOLO
OPEN(15000, FILE=trim(dir_dados)//'Saida/escoamento_Qs.txt', status='unknown',form='formatted')
WRITE(15000,'(A40)') '      QSUP      QSUB      VSUP      VSUB'
IT=0     	

DO WHILE (IT < NT)
	IT=IT+1
    ! ARRUMA AS DATAS
    TEMPO=IHORAINI/24.+FLOAT(IT-1)*DTP/86400
	IHORA=NINT((TEMPO-INT(TEMPO))*24.) ! HORA DA SIMULACAO
	JDIA=IDINI+INT(TEMPO) ! DIA JULIANO DO CALENDÁRIO 
    ! ARRUMA DATAS EM FORMAT CARACTER PARA A SIMULACAO
    CALL CALDAT(JDIA,IMES,IDIA,IANO)
    WRITE(CDATA(1:2),'(I2.2)') IDIA
    WRITE(CDATA(3:4),'(I2.2)') IMES
    WRITE(CDATA(5:8),'(I4)') IANO
    WRITE(CDATA(9:10),'(I2.2)') IHORA
    CDATAG(IT)=CDATA

! EXCLUIDO - MHD-ROUTING GAROFOLO
!	DO IMAPAS=2,NMAPAS
!		IF(IT == ITMAP(IMAPAS))THEN
!			CALL LEUSO(IMAPAS)
!			EXIT
!		ENDIF
!	ENDDO
! VARIAVEIS METEOROLOGICAS NO INTERVALO
!	TONTEM=TA

! GAROFOLO	- COMENTADO POR NÃO UTILIZAR NO ROUTING
!	DO IC2=1,NCDOM
!	    IC=ICDOM(IC2)
!	    PRE(IC)=PREALL(IC,IT) ! PRECIPITACAO NO INTERVALO
!        TA(IC)=TAALL(IC,IT) ! TEMPERATURA DO AR NO INTERVALO
!        TDEW(IC)=TDEWALL(IC,IT) ! TEMPERATURA PONTO DE ORVALHO NO INTERVALO
!        VV(IC)=VVALL(IC,IT) ! VELOCIDADE DO VENTO NO INTERVALO
!        PATM(IC)=PATMALL(IC,IT) ! PRESSAO ATMOSFERICA NO INTERVALO
!        ROC(IC)=ROCALL(IC,IT) ! RADIACAO GLOBAL INCIDENTE NO INTERVALO
!    ENDDO
    
	!SUBROTINA DA CELULA
	CALL CELULA
	
    WRITE(15000,'(4F20.10)')QSUP(1000),QSUB(1000),VSUP(1000),VSUB(1000)
    
	!SUBROTINA DA REDE DE DRENAGEM
	CALL REDE
	
!	IF(NFP>0) THEN
!	    ! SUBROTINA DE ALAGAMENTO
!	    CALL FLOODPLAIN ! VERIFICAR COMO FUNCIONA NO DOMINIO
!	ENDIF

	!ARMAZENA DADOS DE VAZÃO DAS CÉLULAS EM QUE EXISTE VAZÃO OBSERVADA 
	!QR(IB,IT) VAI SER COMPARADO A QOBS(IB,IT) NA ROTINA FOBJ
    !IQOBS(IB) CELULAS QUE CORRESPONDEM AOS POSTOS FLU COM DADOS
    IF(ICALIB == 1) THEN ! ESTA CALIBRANDO
    	QR(NBVFO,IT)=QJ2(IQOBS(NBVFO)) ! SO ARMAZENA O POSTO QUE ESTA SENDO CALIBRADO
   	ELSEIF(ICALIB == 0)THEN !ESTA SIMULANDO
   	    DO IB=1,NB
		    !ARMAZENA VAZOES DAS SUB-BACIAS
		    QRB(IB,IT)=QJ2(IEXUT(IB)) ! IEXUT(IB) CELULA DO EXUTORIO DA SUB-BACIA IB
        ENDDO   	
	    DO IB=1,NOBS
		    QR(IB,IT)=QJ2(IQOBS(IB)) ! POSTOS COM VAZOES OBSERVADAS
	    ENDDO
		DO IB=1,NHIDG !GUARDA DADOS PARA GRAVAR HIDROGRAMAS EM LOCAIS DEFINIDOS NO ARQUIVO PARHIG 
			!IHIDG(K) É O NÚMERO DA CÉLULA EM QUE SE DESEJA O HIDROGRAMA
			QRG(IB,IT)=QJ2(IHIDG(IB)) !QRG ARMAZENA OS HIDROGRAMAS NOS LOCAIS DESEJADOS
	    
		ENDDO	    
	      
!        SOMAD=SUM(PRE(1:NC)*ACEL(1:NC))
!        SOMAAR=SUM(ACEL(1:NC))
!        PMEDDIA=SOMAD/SOMAAR
!        WRITE(FILPMEDIA,'(A10,F10.2)') CDATAG(IT),PMEDDIA
	
	    !************** NOSOLO.HIG ***************************************************************
	    !As linhas abaixo servem para gravar algumas variáveis detalhadas de um bloco e de
	    !uma célula. Os valores de JB e JC podem ser alterados, JU indica o bloco e JC a
	    !célula em que se desejam os dados. Os dados são gravados num arquivo chamado NOSOLO.HIG.
		
		JC=10
		WRITE(FILSOL,'(I6,3F10.3)')IT,QSUB(JC),QSSU(JC),QSUP(JC)
	    !WRITE(*,'(I6,12F10.3)')IT,PRE(JC),ETT(JC,JU),EC(JC,JU),ETP(JC,JU),ASAT(JC,JU),SSSU(JC,JU),SRAD(JC,JU),SSUB(JC,JU),QSUB(JC),QSSU(JC),QSUP(JC)
	    !pause
	    !Fim da saida de dados para o arquivo NOSOLO.HIG
	    !******************************************************************************************
!	    DO IC=1,NC
!		    PREC(IC)=PREC(IC)+PRE(IC) !ACUMULA CHUVA NA CELULA
!	    ENDDO

		!ARMAZENA VAZÕES SEGUNDO A ORIGEM PARA UMA CÉLULA
		! IHIDG(NBVFO) CÉLULA EM QUE SE DESEJAM OS RESULTADOS DE HIDROGRAMA SEPARADO POR ORIGEM
		QBSUB(IT)=QJ2(IHIDG(NBVFO))*PJSUB(IHIDG(NBVFO))
		QBSSU(IT)=QBSSU(IT)+QJ2(IHIDG(NBVFO))*PJSSU(IHIDG(NBVFO))
		QBSUP(IT)=QBSUP(IT)+QJ2(IHIDG(NBVFO))*PJSUP(IHIDG(NBVFO))
		
	ENDIF

ENDDO !FIM DO LOOP DO TEMPO
close(15000)

RETURN
END
