	SUBROUTINE MONTECARLO
	!ESTA SUBROTINA É CHAMADA PARA REALIZAR SIMULACOES CONSECUTIVAS COM VARIACAO DOS PARAMETROS
	
	USE VARS_MAIN
	USE VARS_CALIB

	IMPLICIT NONE
	INTEGER K, INDEX, IB, IU
	!REAL RDAN(MCREC)
    
    DO IB=1,NB
		IRMC=IRMC+1
		WRITE(*,*)'MCREC',MCREC,IRMC
		READ(FILMCUSO,REC=IRMC)(RAUX(K),K=1, MCREC)
		!READ(FILMCUSO,REC=IRMC)RDAN
		WRITE(*,*)'LE',MCREC,IRMC, NU
		INDEX = 0
		DO IU=1,NU-1 ! NAO USA AGUA
			INDEX = INDEX+1
			SMAX(IB,IU) =   SMAX(IB,IU)*RAUX(INDEX)	
			INDEX = INDEX+1
			TSUB(IB,IU) = TSUB(IB,IU)*RAUX(INDEX)
			INDEX = INDEX+1
			KSS(IB,IU) = KSS(IB,IU)*RAUX(INDEX)
			INDEX = INDEX+1
			NETA(IU) = NETA(IU)*RAUX(INDEX)
			INDEX = INDEX+1
			SSMAX(IB,IU) =   SSMAX(IB,IU)*RAUX(INDEX)
			INDEX = INDEX+1
			ALPHA(IB,IU) =   ALPHA(IB,IU)*RAUX(INDEX)
			INDEX = INDEX+1
			CSI(IB,IU) =   CSI(IB,IU)*RAUX(INDEX)
			INDEX = INDEX+1
			MU(IB,IU) =   MU(IB,IU)*RAUX(INDEX)
		ENDDO
	   
	    INDEX = INDEX+1
		CS(IB) =   CS(IB)*RAUX(INDEX)
	    INDEX = INDEX+1
		CB(IB) =   CB(IB)*RAUX(INDEX)
	    INDEX = INDEX+1
		QESP(IB) = QESP(IB)*RAUX(INDEX)
    ENDDO

    RETURN
	END
