SUBROUTINE PARCUNGE
!Esta rotina calcula o valor ideal de
!1- dtcal (intervalo de tempo de calculo da propagação)
!2- NTR (numero de subtrechos em que sera dividida a propagação)
USE VARS_MAIN
IMPLICIT NONE
INTEGER NTR,IC

!	REAL DQ,DA,CELTEMP,HMUP,BTOT,AMENOR,BINUN,PERIM,QPLAN,APLAN,RPLAN,QMENOR !VARIAVEL AUXILIAR
REAL COEF,DTCAL,DX      	!VARIAVEIS AUXILIARES	
REAL ALONG,HFLOW,DECLIV  	!VARIAVEIS AUXILIARES

RUGMAN=0.030 !COEFICIENTE DE MANNING É CONSIDERADO FIXO EM 0,03 PARA TODOS OS TRECHOS E RIOS
ICODMUSK=0 !POR PRINCIPIO CONSIDERA TODAS AS PROPAGACOES POR MUSKINGUN CUNGE LINEAR
DTCAL=MAX(DTP/24.,600.) ! (1 HORA DADOS DIARIOS, 10' DADOS HORARIOS)

DO IC=1,NC !LOOP DAS CÉLULAS

	IF(ACEL(IC)>0.1.AND.ADREN(IC)/ACEL(IC)>1.5)THEN ! CELULAS COM RIO
		COEF=1.67*DECL(IC)**0.3/RUGMAN**0.6
		CEL(IC)=COEF*(QREF(IC)/BRIO(IC))**0.4
		ALONG=SRIO(IC)*1000. !CONVERTE PARA METROS 
  
		! PARECE MAIS ESTAVEL QUE A PROPOSTA POR TUCCI QUE DA PROBLEMAS QUANDO X > 0.4
		! DA VALORES MUITO PARECIDOS AOS DE SZEL & GASPAR SEM OS PROBLEMAS PARA CELERIDADES BAIXAS
		! EQUACAO PROPOSTA POR JONES 1981 
		! DX = 0.5*C*DT*(1+SQRT(1+3.068*DIFUS/(C**2*DT)))
		! DIFUS = Q/(2 S0 B) DIFUSIVIDADE HIDRAULICA
		! DX=0.5*CLX*DTCAL*(1+(1+1.5*(QRX/BRX)/(CLX**2*DECLIV*DTCAL))**0.5)
		! Criterio Fread(1992) Flow Routing, in Handbook of Hydrology, Maidment (muito parecido!!)

		DX=0.5*CEL(IC)*DTCAL*(1+SQRT(1+3.068*QREF(IC)/(2.*DECL(IC)*BRIO(IC)*CEL(IC)*CEL(IC)*DTCAL)))
		NTR=NINT(ALONG/DX) !CALCULA NUMERO DE TRECHOS
		NTR=MAX(NTR,1)
				
		IF(NTR > NTRMAX)THEN 
			WRITE(*,*) 'NUMERO DE SUB-TRECHOS MAIOR QUE', NTRMAX,' NA ROTINA PARCUNGE!!!'
			STOP 'PAROU '
		ENDIF
		
		DT(IC)=DTCAL
		NTRC(IC)=NTR
		
		!WC - mudança dia 20/03/2004 São Francisco: Muskingun Cunge nao linear para algumas celulas
		!IF(ADREN(IC)>185000.0.AND.ADREN(IC)<500000.0) THEN !MUSKINGUN CUNGE NAO LINEAR COM PLANICIE
		!	BPLAN(IC)=12000.0 !LARGURA DA PLANÍCIE INUNDÁVEL EM METROS
		!	HCALHA1(IC)=6.0 !PROFUNDIDADE PARA A QUAL COMEÇA A INUNDAR A PLANÍCIE
		!	HCALHA2(IC)=8.0 !PROFUNDIDADE PARA A QUAL A PLANÍCIE ESTÁ COMPLETAMENTE INUNDADA
		!	RUGPLAN=0.299 !RUGOSIDADE DA PLANÍCIE É MUITO ALTA
		!	
		!	IF(IC>1734.AND.IC<1742)THEN !entre São Francisco e MANGA
		!		DECL(IC)=0.000100
		!		RUGPLAN=0.99
		!		BPLAN(IC)=5000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ELSEIF(IC>=1742.AND.IC<1748)THEN !!entre MANGA E BOM JESUS DA LAPA
		!		DECL(IC)=0.000100
		!		RUGPLAN=0.99
		!		BPLAN(IC)=5000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ELSEIF(IC>=1748.AND.IC<1899)THEN !!entre BOM JESUS DA LAPA E PARATINGA
		!		RUGPLAN=0.09
		!		BPLAN(IC)=6000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ELSEIF(IC>=1899.AND.IC<1902)THEN !!entre PARATINGA E IBOTIRAMA
		!		RUGPLAN=0.09
		!		BPLAN(IC)=6000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ELSEIF(IC>=1902.AND.IC<1904)THEN !!entre IBOTIRAMA E MORPARA
		!		RUGPLAN=0.09
		!		BPLAN(IC)=8000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ELSEIF(IC>=1904.AND.IC<2227)THEN !!entre MORPARA E SOBRADINHO
		!		RUGPLAN=0.09
		!		BPLAN(IC)=8000.0 !LARGURA DA PLANÍCIE
		!		HCALHA1(IC)=6.5 !PROFUNDIDADE PARA A QUAL INICIA A INUNDAÇÃO DA VARZEA
		!		HCALHA2(IC)=7.0 !PROFUNDIDADE PARA VÁRZEA COMPLETAMENTE INUNDADA
		!	ENDIF
		!		
        !
		!	HMUP=0.2
		!	DO KH=1,NTMUP !CRIA UMA TABELA QUE RELACIONA A VAZÃO, PROFUNDIDADE E CELERIDADE PARA MUSKINGUM CUNGE NAO LINEAR
		!		HMUP=HMUP+(HCALHA1(IC)+HCALHA2(IC))/NTMUP !VAI INCREMENTANDO A PROFUNDIDADE
		!		QMENOR=((BRIO(IC)*HMUP)*HMUP**0.6667*DECL(IC)**0.5)/RUGMAN !MANNING PARA A CALHA MENOR
		!		AMENOR=BRIO(IC)*HMUP !ÁREA MOLHADA DA CALHA MENOR
		!		IF(HMUP>HCALHA1(IC))THEN !COMEÇOU A INUNDAR
		!			!CALCULA A LARGURA TOTAL (CALHA MAIOR E MENOR)
		!			IF(HMUP<HCALHA2(IC))THEN
		!				BTOT=BPLAN(IC)*HMUP/HCALHA2(IC) 
		!			ELSE
		!				BTOT=BPLAN(IC)
		!			ENDIF
		!			!CONSIDERA QUE A PLANÍCIE É SIMÉTRICA (ISTO NAO MUDA NADA!)
		!			!CALCULA TRECHO INUNDADO DE CADA LADO
		!			BINUN=(BTOT-BRIO(IC))/2.
		!			!CALCULA PERÍMETRO MOLHADO NA PLANÍCIE (DE CADA LADO)
		!			PERIM=(BINUN**2.+(HMUP-HCALHA1(IC))**2.)**0.5 !
		!			APLAN=BINUN*(HMUP-HCALHA1(IC))
		!			RPLAN=APLAN/PERIM !RAIO HIDRÁULICO NA PLANÍCIE
		!			IF(HMUP-HCALHA1(IC)<=1.0)THEN
		!				RUGPLAN=0.9
		!			ELSEIF(HMUP-HCALHA1(IC)<=2.0)THEN
		!				RUGPLAN=0.7
		!			ELSEIF(HMUP-HCALHA1(IC)<=3.0)THEN
		!				RUGPLAN=0.4
		!			ELSEIF(HMUP-HCALHA1(IC)<=4.0)THEN
		!				RUGPLAN=0.4
		!			ELSE
		!				RUGPLAN=0.4
		!			ENDIF
		!			QPLAN=(APLAN*RPLAN**0.6667*DECL(IC)**0.5)/RUGPLAN
		!			QPLAN=2.*QPLAN !UMA PARTE DE PLANÍCIE DE CADA LADO DO RIO
		!			APLAN=2.*APLAN !IDEM
		!		ELSE
		!			QPLAN=0.0
		!			APLAN=0.0
		!			BTOT=BRIO(IC)
		!		ENDIF
		!		QMUP(IC,KH)=QMENOR+QPLAN
		!		AMUP(IC,KH)=AMENOR+APLAN
		!		BMUP(IC,KH)=BTOT
		!	ENDDO
        !
		!	DO KH=1,NTMUP-1
		!		DQ=QMUP(IC,KH+1)-QMUP(IC,KH)
		!		DA=AMUP(IC,KH+1)-AMUP(IC,KH)
		!		CELTEMP=DQ/DA !CALCULA A CELERIDADE
		!		QMUP(IC,KH)=0.5*(QMUP(IC,KH)+QMUP(IC,KH+1))
		!		AMUP(IC,KH)=0.5*(AMUP(IC,KH)+AMUP(IC,KH+1))
		!		BMUP(IC,KH)=0.5*(BMUP(IC,KH)+BMUP(IC,KH+1))
		!		CMUP(IC,KH)=CELTEMP !GUARDA CELERIDADE PARA A VAZAO INDICADA
		!		!WRITE(*,*)IC,KH,QMUP(IC,KH),AMUP(IC,KH),BMUP(IC,KH),CMUP(IC,KH)
		!	ENDDO
		!	QMUP(IC,NTMUP)=QMUP(IC,NTMUP) !O ULTIMO PONTO NAO MUDA
		!	CMUP(IC,NTMUP)=CMUP(IC,NTMUP-1) !PARA A CELERIDADE USA ULTIMO PONTO CALCULADO
		!	BMUP(IC,NTMUP)=BMUP(IC,NTMUP-1) !MESMA COISA PARA A LARGURA
		!	ICODMUSK(IC)=1 !INDICA MUSKINGUN CUNGE NAO LINEAR
		!	IF(IC>=1904.AND.IC<2227)THEN !!entre MORPARA E SOBRADINHO
		!		QMUP(IC,1)=300.0
		!		QMUP(IC,2)=2000.0
		!		QMUP(IC,3)=3000.0
		!		QMUP(IC,4)=4000.0
		!		QMUP(IC,5)=5000.0
		!		QMUP(IC,6)=6000.0
		!		QMUP(IC,7)=7000.0
		!		QMUP(IC,8)=8000.0
		!		QMUP(IC,9)=9000.0
		!		QMUP(IC,10)=1000.0
		!		QMUP(IC,11)=11000.0
		!		QMUP(IC,12)=12000.0
		!		QMUP(IC,13)=13000.0
		!		QMUP(IC,14)=14000.0
		!		QMUP(IC,15)=15000.0
		!		QMUP(IC,16)=16000.0
		!		QMUP(IC,17)=17000.0
		!		QMUP(IC,18)=18000.0
		!		QMUP(IC,19)=19000.0
		!		QMUP(IC,20)=20000.0
        !
		!		CMUP(IC,1)=1.2
		!		CMUP(IC,2)=1.2
		!		CMUP(IC,3)=1.2
		!		CMUP(IC,4)=1.3
		!		CMUP(IC,5)=1.4
		!		CMUP(IC,6)=0.7
		!		CMUP(IC,7)=0.3
		!		CMUP(IC,8)=0.3
		!		CMUP(IC,9)=0.4
		!		CMUP(IC,10)=0.5
		!		CMUP(IC,11)=0.5
		!		CMUP(IC,12)=0.55
		!		CMUP(IC,13)=0.6
		!		CMUP(IC,14)=0.6
		!		CMUP(IC,15)=0.6
		!		CMUP(IC,16)=0.6
		!		CMUP(IC,17)=0.6
		!		CMUP(IC,18)=0.6
		!		CMUP(IC,19)=0.6
		!		CMUP(IC,20)=0.6
        !
		!	ENDIF
        !
		!	
		!ELSE
		!	ICODMUSK(IC)=0 !INDICA MUSKINGUN CUNGE LINEAR
		!ENDIF !


	ELSE !AREAS FONTE (SINKS), SEM RIO, NAO INTERESSAM
		DT(IC)=0.0
		NTRC(IC)=0
	ENDIF

ENDDO !FIM DO LOOP DAS CÉLULAS

IF(NFP > 0) THEN ! EXISTEM CELULAS COM PLANICIE DE ALAGAMENTO	
    ! DEFINE O PASSO DE TEMPO PARA O CALCULO NA PLANICIE (HUNTER ET AL. 
    DX=SQRT(ACEL(ICELLFP(1))) ! DISTANCIA ENTRE CELULAS DA PLANICIE
    DECLIV=0.01/DX ! DECLIVIDADE MINIMA ENTRE CELULAS DE PLANICIE (ADMITINDO 1 CM NA DIFERENCA DE COTA ENTRE ELEMNTOS)
    HFLOW=2. ! MAXIMA COTA NO ELEMENTO DE PLANICIE EM METROS
    DTFP=DX**2/4.*(2*RUGMAN*DECLIV**0.5/HFLOW**1.667)
    DTFP=DTP
ENDIF

RETURN
END