	SUBROUTINE PREVISAO
	!Esta subrotina comanda o loop do tempo do modelo hidrológico e chama as 
	!rotinas de balanco e propagação nas células e de propagação na rede de drenagem
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER IC,IB,IU
	INTEGER K,KHID !CONTADORES
	INTEGER KB,JCB,MWP 	!CONTADORES
	INTEGER IHORIZ,IMAPAS
	REAL TEMPO ! TEMPO DE SIMULACAO EM DIAS
	REAL VBX
	CHARACTER CDATAL*16

	! DOMINCIO DA SIMULACAO
	NCDOM=NC
	DO IC=1,NC
	    ICDOM(IC)=IC ! POR ENQUANTO, SIMULA TODO O DOMINIO NA ROTINA PREVISAO
	ENDDO
	!VETOR COM A SEQUENCIA DE CELULAS COM AREAS DRENADA CRESCENTE USADOS NA RESOLUCAO NA ROTINA REDE
	CALL SORT(NC,ADREN,IDREN)
    CALL MODELO ! EXECUTA O MODELO NO MODO SIMULACAO ATE O DIA DO INICIO DA PREVISAO

	!GUARDA VALORES DAS VARIÁVEIS ANTES DE COMEÇAR O CICLO DE PREVISÃO
	OPEN(FILCCINI,FILE=DIR_DADOS//'CCINI_'//CDATA//'.BIN', STATUS='UNKNOWN',FORM='UNFORMATTED',RECORDTYPE='STREAM')
!	WRITE(FILCCINI) ((SSSU(IC,IU),IU=1,NU),IC=1,NC)
!	WRITE(FILCCINI) ((SRAD(IC,IU),IU=1,NU),IC=1,NC)
!	WRITE(FILCCINI) ((SSUB(IC,IU),IU=1,NU),IC=1,NC)
	!DOS RESERVATORIOS SUBTERRANEO, SUBSUPERFICIAL E SUPERFICIAL
	WRITE(FILCCINI) VSUP
	WRITE(FILCCINI) VSSU
	WRITE(FILCCINI) VSUB
!	WRITE(FILCCINI) TA
	WRITE(FILCCINI) QM2
	WRITE(FILCCINI) QJ2
	WRITE(FILCCINI) NTRC
	WRITE(FILCCINI) QRIOINI
	WRITE(FILCCINI) QCEL2
	WRITE(FILCCINI) PMSUB
	WRITE(FILCCINI) PMSSU
	WRITE(FILCCINI) PMSUP
	WRITE(FILCCINI) VRSUB
	WRITE(FILCCINI) VRSSU
	WRITE(FILCCINI) VRSUP
	IF(NFP>0) THEN
    	WRITE(FILCCINI) VFP
	    WRITE(FILCCINI) AFP
	    WRITE(FILCCINI) QRFP
	ENDIF
	CLOSE(FILCCINI)
	
    !CHAMA A SUBROTINA DE ASSIMILACAO DE DADOS PARA ATUALIZAR O MODELO DO ULTIMO PASSO DE TEMPO
	CALL ATUALIZA

	!CICLO DE PREVISÃO 
    !grava informações no arquivo diário
    OPEN(FILPREVFIN,FILE=DIR_DADOS//'SAIDA/'//'PREV_'//CDATA//'.HIG',STATUS='UNKNOWN') ! ARQUIVO COM A PREVISAO
	WRITE(FILPREVFIN,'(A22,A10)') ' PREVISAO INICIADA EM ',CDATA	
	Write(FILPREVFIN,*)
	
	! GRAVA CONDICAO INICIAL
	CDATAL=CDATAG(IT)(1:2)//'/'//CDATAG(IT)(3:4)//'/'//CDATAG(IT)(5:8)//' '//CDATAG(IT)(9:10)//':00'
	WRITE(FILPREVFIN,'(A16,<NHIDG>F10.3)') CDATAL,(QJ2(IHIDG(K)),K=1,NHIDG) 
	
    DO WHILE (IT < NT+NTPREV)
    
	    IT=IT+1
        TEMPO=IHORAINI/24.+FLOAT(IT-1)*DTP/86400
    	IHORA=NINT((TEMPO-INT(TEMPO))*24.) ! HORA DA SIMULACAO
		JDIA=IDINI+INT(TEMPO) ! DIA JULIANO DO CALENDÁRIO 
				
		CALL CALDAT(JDIA,IMES,IDIA,IANO)
		WRITE(CDATA(1:2),'(I2.2)') IDIA
        WRITE(CDATA(3:4),'(I2.2)') IMES
        WRITE(CDATA(5:8),'(I4)') IANO    
        WRITE(CDATA(9:10),'(I2.2)') IHORA
		CDATAG(IT)=CDATA
			
		!SUBROTINAS DE LEITURA E PREPARACAO DE DADOS METEOROLOGICOS E DE CHUVA
		!CALL LEMETPREV    ! LE DADOS DE CHUVA E METEOROLOGICOS PARA CALCULAR EVAPORACAO
!		DO IC=1,NC
!			PREC(IC)=PREC(IC)+PRE(IC) !ACUMULA CHUVA NA CELULA
!		ENDDO
	
		!SUBROTINA QUE VERIFICA A QUALIDADE DOS DADOS METEOROLOGICOS
!		TONTEM=TA
		!SUBROTINA DA CELULA
		CALL CELULA
		!SUBROTINA DA REDE DE DRENAGEM
		CALL REDE
!		IF(NFP>0) THEN
!		    ! SUBROTINA DE ALAGAMENTO
!		    CALL FLOODPLAIN
!		ENDIF
		DO K=1,NHIDG !GUARDA DADOS PARA GRAVAR HIDROGRAMAS EM LOCAIS DEFINIDOS NO ARQUIVO PARHIG 
			! IHIDG(K) É O NÚMERO DA CÉLULA EM QUE SE DESEJA O HIDROGRAMA
			QPREV(K,IT-NT)=QJ2(IHIDG(K)) !QPREV HIDROGRAMAS PREVITOS NOS LOCAIS DESEJADOS
		ENDDO

	ENDDO !FIM DO LOOP DE TEMPO
	
	DO IT=NT+1,NT+NTPREV
		!GRAVA ARQUIVO DE HIDROGRAMA DE PREVISÃO
    	CDATAL=CDATAG(IT)(1:2)//'/'//CDATAG(IT)(3:4)//'/'//CDATAG(IT)(5:8)//' '//CDATAG(IT)(9:10)//':00'
		WRITE(FILPREVFIN,'(A16,<NHIDG>F10.3)') CDATAL,(QPREV(K,IT-NT),K=1,NHIDG) 
    ENDDO
    CLOSE(FILPREVFIN)

    DEALLOCATE(QPREV)
    
71	FORMAT(I10,20F10.3)
75	FORMAT(I6,28F7.0)	
76  FORMAT(A100)
79	FORMAT(I10)		
	RETURN
	END

