SUBROUTINE REDEINI
!ESTA ROTINA INICIALIZA A REDE DE DRENAGEM NO PRIMEIRO PASSO DE TEMPO QUANDO NAO EXISTEM CONDICOES INICIAIS 
USE VARS_MAIN
IMPLICIT NONE
INTEGER NTR,NTCLAST !NUMERO DE SUBTRECHOS, NUMERO DE SUBINTERVALOS
!PROPORÇÕES DE ORIGEM
REAL QAUX
INTEGER LT,JUS
INTEGER IB,IC,IC2,J !CONTADORES

! NUMERO DE INTERVALO DE TEMPO PARA RESOLVER MC EM CADA CELULA, FIXADO A PARTIR 
! DA ÚLTIMA CELULA QUE TEM O MAIOR INTERVALO DE TEMPO
NTCLAST=DTP/DT(NC)

!CONDIÇÕES INICIAIS DA VAZAO NO RIO
QJ2=0.0
QM2=0.0
PMSUB=0.0
PMSSU=0.0
PMSUP=0.0
QCEL1=0.0
QCEL2=0.0
QRIOINI=0.0
VRSUB=0.0
VRSSU=0.0
VRSUP=0.0
QCONTORM=0.
QCONTORJ=0.

DO IC2=1,NCDOM ! LOOP SOBRE AS CELULAS DO DOMINIO
    IC=IDREN(IC2)
	IF(NTRC(IC) > 0)THEN	!CELULA COM RIO
		!TRANSFORMA PROPORÇÕES EM VAZÕES		
		PMSUB(IC)=PMSUB(IC)*QM2(IC) !VAZAO SUBTERRANEA
		PMSSU(IC)=PMSSU(IC)*QM2(IC) !VAZAO SUB-SUPERFICIAL
		PMSUP(IC)=PMSUP(IC)*QM2(IC) !VAZÃO SUPERFICIAL
			
		!ACUMULA VAZAO DE MONTANTE MAIS VAZAO NA CELULA
		QM2(IC)=MAX(QM2(IC)+QSUP(IC)+QSSU(IC)+QSUB(IC),0.000001)
!		IF(IC==172) WRITE(*,*) '1 - 172 REDEINI:',QM2(JUS),QSUP(IC),QSSU(IC),QSUB(IC),QM2(IC)+QSUP(IC)+QSSU(IC)+QSUB(IC)	
		!ATUALIZA PROPORÇÕES
		PMSUB(IC)=(PMSUB(IC)+QSUB(IC))/QM2(IC)
		PMSSU(IC)=(PMSSU(IC)+QSSU(IC))/QM2(IC)
		PMSUP(IC)=(PMSUP(IC)+QSUP(IC))/QM2(IC)

		!CONDIÇÃO DE CONTORNO MUSKINGUM-CUNGE DE MONTANTE
		DO LT=1,NTCLAST+1
			QCONTORM(IC,LT)=QCONTORM(IC,LT)+QM2(IC)
		ENDDO

       ! PROPAGA PARA JUSANTE
		JUS=CELJUS(IC)
		QJ2(IC)=QM2(IC)	!VAZAO CONSTANTE NO TRECHO COM CONDICAO INICIAL

		!CONDIÇÃO DE CONTORNO MUSKINGUM-CUNGE DE JUSANTE
		DO LT=1,NTCLAST+1
			QCONTORJ(IC,LT)=QCONTORJ(IC,LT)+QJ2(IC)
		ENDDO
			
		!A PROPORÇÃO QUE ENTRA SAI
		PJSUB(IC)=PMSUB(IC)
		PJSSU(IC)=PMSSU(IC)
		PJSUP(IC)=PMSUP(IC)
			
		! TRANSFORMA PROPORCAO EM VAZAO
		PMSUB(JUS)=PMSUB(JUS)*QM2(JUS) !VAZÃO SUBTERRANEA
		PMSSU(JUS)=PMSSU(JUS)*QM2(JUS) !VAZÃO SUB-SUPERFICIAL
		PMSUP(JUS)=PMSUP(JUS)*QM2(JUS) !VAZÃO SUPERFICIAL

		!O QUE SAI DO RIO DE UMA CEL. VAI PRA OUTRA
		QM2(JUS)=MAX(QM2(JUS)+QJ2(IC),0.00001) 
!        IF(IC==172) WRITE(*,*) '1- 172 REDEINI:',QM2(JUS),QJ2(IC),QM2(JUS)+QJ2(IC)
!        IF(IC==98) WRITE(*,*) '1 - 98 REDEINI:',QM2(JUS),QJ2(IC),QM2(JUS)+QJ2(IC)
        
		!ATUALIZA PROPORÇÕES
		PMSUB(JUS)=(PMSUB(JUS)+PJSUB(IC)*QJ2(IC))/QM2(JUS)  
		PMSSU(JUS)=(PMSSU(JUS)+PJSSU(IC)*QJ2(IC))/QM2(JUS)
		PMSUP(JUS)=(PMSUP(JUS)+PJSUP(IC)*QJ2(IC))/QM2(JUS)

		!TENTATIVA DE PROPORÇÕES
		QAUX=(QM2(IC)+QJ2(IC))/2
		VRSUB(IC)=0.3333*(1000.*SRIO(IC)*QAUX/CEL(IC))
		VRSSU(IC)=0.3333*(1000.*SRIO(IC)*QAUX/CEL(IC))
		VRSUP(IC)=0.3333*(1000.*SRIO(IC)*QAUX/CEL(IC))

	ELSE !CELULA FONTE
		JUS=CELJUS(IC)
		PMSUB(JUS)=PMSUB(JUS)*QM2(JUS) !VAZÃO SUBTERRANEA
		PMSSU(JUS)=PMSSU(JUS)*QM2(JUS) !VAZÃO SUB-SUPERFICIAL
		PMSUP(JUS)=PMSUP(JUS)*QM2(JUS) !VAZÃO SUPERFICIAL

		QM2(JUS)=MAX(QM2(JUS)+QSUP(IC)+QSSU(IC)+QSUB(IC),0.000001)
!        IF(IC==172) WRITE(*,*) '2-172 REDEINI:',QM2(JUS),QSUP(IC),QSSU(IC),QSUB(IC),QM2(JUS)+QSUP(IC)+QSSU(IC)+QSUB(IC)
!        IF(IC==98) WRITE(*,*) '2-98 REDEINI:',QM2(JUS),QSUP(IC),QSSU(IC),QSUB(IC),QM2(JUS)+QSUP(IC)+QSSU(IC)+QSUB(IC)
		!CONDIÇÃO DE CONTORNO MUSKINGUM-CUNGE
		DO LT=1,NTCLAST+1
			QCONTORM(JUS,LT)=QCONTORM(JUS,LT)+QM2(JUS)
			
		ENDDO

		!ATUALIZA PROPORÇÕES
		PMSUB(JUS)=(PMSUB(JUS)+QSUB(IC))/QM2(JUS)  
		PMSSU(JUS)=(PMSSU(JUS)+QSSU(IC))/QM2(JUS)
		PMSUP(JUS)=(PMSUP(JUS)+QSUP(IC))/QM2(JUS)

	ENDIF
ENDDO
!FIM DAS CONDIÇÕES INICIAIS
RETURN
END
