SUBROUTINE SIMULA
!ESTA SUBROTINA É CHAMADA QUANDO O PROBLEMA É DE SIMULAÇÃO, NÃO É FEITA A CALIBRAÇÃO
USE VARS_MAIN
!!!!USE VARS_CALIB
IMPLICIT NONE
INTEGER K,IC,IB
CHARACTER SUBBAC*2,CDATAL(NT)*16

!	
! DOMINIO DA SIMULACAO
!
NCDOM=NC
DO IC=1,NC
    ICDOM(IC)=IC ! POR ENQUANTO, SIMULA TODO O DOMINIO NA ROTINA SIMULACAO 
ENDDO

!VETOR COM A SEQUENCIA DE CELULAS COM AREAS DRENADA CRESCENTE USADOS NA RESOLUCAO NA ROTINA REDE
CALL SORT(NC,ADREN,IDREN)

! ARQUIVO DE CHUVA DIARIA DA BACIA
!OPEN(FILPMEDIA,FILE=DIR_DADOS//'Saida/CHUVA_DIARIA_MEDIA.TXT',STATUS='UNKNOWN') 

!************** NOSOLO.HIG ***************************************************************
! GRAVA DADOS DETALHADOS DE UM BLOCO DE UMA CELULA.  
!ARQUIVO DE SAIDA COM DADOS DO SOLO DE UMA CELULA       
OPEN(FILSOL,FILE=DIR_DADOS//'Saida/NOSOLO.HIG',STATUS='UNKNOWN')	

! TITULOS DOS ARQUIVOS
!WRITE(FILSOL,'(A116)') 'CELULA    PRECIP       ETT        EC       ETP      ASAT      SSSU      SRAD      SSUB      QSUB      QSSU      QSUP'
WRITE(FILSOL,'(A116)') 'CELULA    QSUB      QSSU      QSUP'
	
!ZERANDO VARIAVEIS DO BALANÇO HIDRICO DA BACIA
!PREC=0.0 ! PRECIPITACAO ACUMULADA NA CELULA
!PREB=0.0 !PRECIPITACAO NA BACIA
!ECB=0.0 ! LAMINA INTERCEPTADA NA BACIA
!ETTB=0.0 ! EVAPOTRANSPIRAÇÃO NA BACIA
!ETPB=0.0   ! TRANSPIRACAO POTENCIAL NA BACIA
!SSSUB=0.0  ! LAMINA ARMAZENADA MEDIA CAMADA SUPERIOR NA BACIA
!SRADB =0.0 ! LAMINA ARMAZENADA MEDIA NA CAMADA INTERMEDIARIA DA BACIA
!SSUBB=0.0 !LAMINA ARMAZENADA MEDIA CAMADA INFEIROR NA BACIA
!ASATB=0.0 !AREA SATURADA MEDIA NA BACIA
DSUPB=0.0 !ESCOMENTO SUPERFICIAL DA BACIA
DSSUB=0.0 !ESCOMENTO INTERMEDIARIO DA BACIA
DSUBB=0.0 !ESCOMENTO SUBTERRANEO DA BACIA
QBSUP=0.0 !VAZAO SUPERFICIAL
QBSSU=0.0 !VAZAO SUB-SUPERFICIAL
QBSUB=0.0 !VAZAO DE BASE


CALL MODELO !CHAMA A ROTINA QUE COMANDA O LOOP DO TEMPO

! CRIA AS DATAS LONGAS PARA O EXCEL
DO IT=1,NT
    CDATAL(IT)=CDATAG(IT)(1:2)//'/'//CDATAG(IT)(3:4)//'/'//CDATAG(IT)(5:8)//' '//CDATAG(IT)(9:10)//':00'
ENDDO

! ABRE ARQUIVOS COM RESULTADOS DA SIMULACAO
DO IB=1,NB
    WRITE(SUBBAC,'(I2.2)') IB
    !ARQUIVO DE SAIDA COM DADOS DAS BACIAS
    OPEN(FILBAC+IB-1,FILE=DIR_DADOS//'Saida/BACIA'//SUBBAC//'.HIG',STATUS='UNKNOWN') 
    WRITE(FILBAC+IB-1,'(A23,I5)') 'DADOS MEDIOS DA BACIA: ',IB
    WRITE(FILBAC+IB-1,'(A52)') '            DATA        QSUP        QSSU        QSUB'
    WRITE(FILBAC+IB-1,'(A52)') '                          mm          mm          mm'

ENDDO
OPEN(FILPRP,FILE=DIR_DADOS//'Saida/QPROP.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAÍDA COM VAZÕES SEGUNDO A ORIGEM
OPEN(FILHID,FILE=DIR_DADOS//'Saida/VAZAO.HIG',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM HIDROGRAMAS CALCULADOS

!GRAVA HIDROGRAMAS NOS NB EXUTORIOS DESEJADOS 
WRITE(FILHID,'(A16,<NHIDG>F15.3)') (CDATAL(IT),(QRG(IB,IT),IB=1,NHIDG),IT=1,NT)
!GRAVA VALORES MEDIOS DAS VARIAVEIS DAS SUB-BACIAS
DO IB=1,NB
    WRITE(FILBAC+IB-1,'(A16,3F12.3)')  (CDATAL(IT),DSUPB(IB,IT),DSSUB(IB,IT),DSUBB(IB,IT),IT=1,NT)
    CLOSE(FILBAC+IB-1)
ENDDO
!GRAVA ARQUIVO COM AS VAZÕES SEGUNDO A ORIGEM
WRITE(FILPRP,'(A16,3F20.3)') (CDATAL(IT),QBSUP(IT),QBSSU(IT),QBSUB(IT),IT=1,NT)
CLOSE (FILHID)
CLOSE (FILPRP)


! GAROFOLO - COMENTADO MHD-ROUTING POR NÃO COMPARAÇÃO COM SÉRIE OBSERVADA E NÃO HAVER PRECIPITAÇÃO	
!CALL FOBJ !CALCULA OS VALORES DAS FUNÇÕES OBJETIVO
!CALCULA PRECIPITAÇÃO MÉDIA ANUAL POR BACIA
!PREBANUAL=0.0
!KBANUAL=0
!PREC=(PREC/NT)*(365.*24.*3600./DTP)
!
!DO IC=1,NC
!	IB=IBAC(IC)
!	PREBANUAL(IB)=PREBANUAL(IB)+PREC(IC)
!	KBANUAL(IB)=KBANUAL(IB)+1.
!ENDDO
!DO IB=1,NB
!	PREBANUAL(IB)=PREBANUAL(IB)/KBANUAL(IB)
!ENDDO
!
!!FIM DO CALCULO DA PRECIPITAÇÃO MÉDIA ANUAL POR BACIA
!WRITE(*,*)'   CHUVA ANUAL NA BACIA ',NBVFO,PREBANUAL(NBVFO)

!CLOSE (FILPMEDIA) ! ARQUIVO DE CHUVA DA BACIA

CALL balanco

RETURN
END
